### ISSUE TITLE
DocumentSemanticTokensRequest always fail

### ISSUE THREAD

**Issue by krzyzanowskim** [apple/sourcekit-lsp#1009]
Requesting semanic tokens does not work, however it used to work

Sending `DocumentSemanticTokensRequest` to the sourcekit-lsp ends up with `unknown request: source.request.semantic_tokens` (which is silenced in tests) with `XCTSkip("semantic tokens request not supported by sourcekitd")`. That is today's state. 

In the past, probably before the https://github.com/apple/sourcekit-lsp/pull/912 server send `WorkspaceSemanticTokensRefreshRequest` with tokens, but also sending `DocumentSemanticTokensRequest` worked with tokens.

It seems something is missing that it no longer works (or what am I missing?)

I confirmed it works with sourcekit-lsp shipped with Xcode 15.1 (15C65), so that looks like regression to me.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://120124113

**Comment by bnbarham** [comment]
`DocumentSemanticTokensRequest` requires a new sourcekitd that has the `source.request.semantic_tokens` request, which would require using a recent development snapshot from https://www.swift.org/download/#trunk-development-main and setting the `SOURCEKIT_TOOLCHAIN_DIR` environment variable to the downloaded toolchain.

We could maybe fallback the tokens from the syntax tree in this case though.

**Comment by krzyzanowskim** [comment]
yes, wonder whether we can fallback to whatever was used pre-swift 9.10?

**Comment by bnbarham** [comment]
> yes, wonder whether we can fallback to whatever was used pre-swift 9.10?

Not easily, there's a lot of back and forth that needs to happen for the old way of retrieving token. It would also mean we couldn't send `syntactic_only` in the open request, which in turn wouldn't allow us to cancel building the AST on a change.

**Comment by krzyzanowskim** [comment]
Do you think we should close as wontfix?

The problem is that `sourcekit-lsp` requires toolchain 5.10 or newer and will fail when used with an earlier version of the toolchain. 

Now, I'd like to know if there's any reasonable action to remove semantic tokens when an incompatible toolchain is detected. In that scenario server should not report semantic tokens capability available to the client. wdyt?

**Comment by bnbarham** [comment]
We should keep open. In the worst case we can fallback to tokens from the syntax tree. Or as you said, not report semantic tokens capability.

**Comment by ahoppen** [comment]
What’s your use case of using a newer sourcekit-lsp than sourcekitd? Generally, sourcekit-lsp is expected to be used with the sourcekitd it comes bundled with. Rename, for example, will also only work if sourcekit-lsp is used with a sourcekitd that supports it.

**Comment by krzyzanowskim** [comment]
> What’s your use case of using a newer sourcekit-lsp than sourcekit

I use forked sourcekit-lsp binary

**Comment by ahoppen** [comment]
So, just to make sure I understand correctly: You fork `sourcekit-lsp` from `main`, build it and use that version with `sourcekitd` from the latest Swift release?

**Comment by benjiwolff** [comment]
Hi, after a bit of fiddling I got the semantic tokens to work in Neovim. I built `sourcekit-lsp` from source and ran it with the latest development toolchain (i. e. with environment variable `SOURCEKIT_TOOLCHAIN_PATH="/Library/Developer/Toolchains/swift-latest.xctoolchain"`). 

However, `sourcekit-lsp` currently does not announce that it supports semantic tokens so I had to add `semanticTokensProvider` to [SourceKitServer](https://github.com/apple/sourcekit-lsp/blob/d5b06c88ed1848ef65d8457ea2be0e9bef129659/Sources/SourceKitLSP/SourceKitServer.swift#L1161) (simply copy-pasted from [SwiftLanguageServer](https://github.com/apple/sourcekit-lsp/blob/d5b06c88ed1848ef65d8457ea2be0e9bef129659/Sources/SourceKitLSP/Swift/SwiftLanguageServer.swift#L246)).

I am not sure why there are multiple definitions for the server capabilities, could someone please explain?

**Comment by ahoppen** [comment]
sourcekit-lsp dynamically registers the semanticTokens capability here

https://github.com/apple/sourcekit-lsp/blob/d5b06c88ed1848ef65d8457ea2be0e9bef129659/Sources/SourceKitLSP/SourceKitServer.swift#L1215-L1219

The problem is that neovim doesn’t support dynamic capability registration. Fixing that by declaring all capabilities statically is something that’s on by mind already.

**Comment by mattmassicotte** [comment]
Wow I'm surprised neovim doesn't support this! I know of at least one other language server, gopls (Go), that works exactly the same way.
