### ISSUE TITLE
Bullets in doc comments rendered as "Discussion," labels are dropped.

### ISSUE THREAD

**Issue by dabrahams** [apple/sourcekit-lsp#1014]
For example, in all clients I can get my hands on:

```
  /// Returns a sequence whose elements describe each rule being recognized at
  /// `position`, where the rule started, and how many of its RHS symbols have
  /// been recognized.
  ///
  /// - Precondition: no other progress report for `self` exists.
```

The precondition is rendered as 

> **Discussion**
>
> no other progress report for `self` exists.

Which is really misleading.  Even if “Discussion” is unavoidable, the bullet label should be preserved (perhaps unless it is exactly “`Discussion`”)

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://120685874
