### ISSUE TITLE
Malformed `compile_commands.json` causes crash

### ISSUE THREAD

**Issue by z2oh** [apple/sourcekit-lsp#1019]
[`tryLoadCompilationDatabase`](https://github.com/apple/sourcekit-lsp/blob/e8e4fb210616e8d41f5803f19dd6427fc27e247e/Sources/SKCore/CompilationDatabase.swift#L71-L93C2) fails aggressively if it finds a `compile_commands.json` but fails to parse it:

```
SKCore/CompilationDatabase.swift:84: Fatal error: 'try!' expression unexpectedly raised an error: Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Foundation.JSONError.unexpectedEndOfFile)))
```

Simple repro:
```
touch A.swift
touch compile_commands.json
code .
```
The language server crashes on startup.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://120804823
