### ISSUE TITLE
sourcekit-lsp no longer starts because ParsableCommand is not implemented properly

### ISSUE THREAD

**Issue by benjiwolff** [apple/sourcekit-lsp#1023]
In [this PR](https://github.com/apple/sourcekit-lsp/pull/1018) the signature of the SourceKitLSP command was changed from
```
func run() throws
```
to
```
func run() async throws
```

Unfortunately, this does not result in a build error. Instead, the `run` function is now simply not recognized. When starting the server from the command-line exits with code 0 and simply shows the CLI manual.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://120976054

**Comment by ahoppen** [comment]
Thanks for the report, @benjiwolff. I’m fixing it in https://github.com/apple/sourcekit-lsp/pull/1024
