### ISSUE TITLE
VSCode stuck on "Reloading Package"

### ISSUE THREAD

**Issue by z2oh** [apple/sourcekit-lsp#1050]
This could be an issue with the Swift extension, but I'm seeing some log output from sourcekit-lsp that looks like it's kicking off this job:
```
[org.swift.sourcekit-lsp:notification-2] info 2024-02-13 10:38:33.104
Sending request to client (id: 1):
window/workDoneProgress/create
{
  "token" : "SourceKitLSP.SourceKitServer.reloadPackage"
}
---
[Trace - 10:38:33 AM] Received request 'window/workDoneProgress/create - (1)'.
Params: {
    "token": "SourceKitLSP.SourceKitServer.reloadPackage"
}
---
[org.swift.sourcekit-lsp:default] info 2024-02-13 10:38:33.107
Sending notification to client
$/progress
{
  "token" : "SourceKitLSP.SourceKitServer.reloadPackage",
  "value" : {
    "kind" : "begin",
    "title" : "Reloading Package"
  }
}
---
[Trace - 10:38:33 AM] Received notification '$/progress'.
Params: {
    "value": {
        "title": "Reloading Package",
        "kind": "begin"
    },
    "token": "SourceKitLSP.SourceKitServer.reloadPackage"
}
```
This is despite launching with a compilation database workspace (I would expect the `reloadPackage` job to only run in a SwiftPM workspace). Maybe a sub-project (not at the root) is being picked up as a SwiftPM workspace?
```
[org.swift.sourcekit-lsp:notification-22] info 2024-02-13 10:59:35.042
SwiftPM log: [info]: using 'Package.resolved' file as lock file
---
[org.swift.sourcekit-lsp:default] default 2024-02-13 10:59:35.797
SwiftPM log: [warning]: C:\workspace\<snip>\<snip>\.build\repositories\swift-argument-parser-54a11a8d is not valid git repository for 'https://github.com/apple/swift-argument-parser.git', will fetch again.
---
[org.swift.sourcekit-lsp:notification-22] debug 2024-02-13 10:59:36.221
SwiftPM log: [debug]: loading manifest for 'swift-sentry' v. unknown from memory cache
---
[org.swift.sourcekit-lsp:notification-22] debug 2024-02-13 10:59:36.227
SwiftPM log: [debug]: loading manifest for 'swift-identified-collections' v. 1.0.0 from memory cache
```
This doesn't seem to impact LSP functionality, but there's a constantly spinning "Reloading Package" notification in the bottom bar
![image](https://github.com/apple/sourcekit-lsp/assets/385684/66dec4c7-1cf8-4d05-8f2b-7cd36eaaed20)

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://122899093

**Comment by adam-fowler** [comment]
This is most likely a VSCode issue, although I don't know if it is coming from the swift extension as it never displays a status item with the text `Reloading Package`

**Comment by ahoppen** [comment]
Based on the logs, this looks like SourceKit-LSP issue to me. We appear to be sending a begin for package reloading but no end.

**Comment by adam-fowler** [comment]
Oh you're right there. Didn't release the progress stuff got displayed in VSCode

**Comment by adam-fowler** [comment]
Is it worthwhile prefixing all sourcekit-lsp progress items with `SourceKit-LSP: ` so we know where the UI is coming from?
