### ISSUE TITLE
`textDocument/definition` returns duplicate results when called on constructors

### ISSUE THREAD

**Issue by benjiwolff** [apple/sourcekit-lsp#1055]
Similar to #1047, sourcekit-lsp returns duplicate results for `textDocument/definition` when called on a constructor. This happens for both value and reference types. The same does not happen when called on the type itself e. g. in a variable declaration.

<img width="781" alt="image" src="https://github.com/apple/sourcekit-lsp/assets/103897890/f7b6bace-4c30-46c4-96c8-205f7e14791f">

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://123036565
