### ISSUE TITLE
Is `textDocument/inlayHint` supported?

### ISSUE THREAD

**Issue by wojciech-kulik** [apple/sourcekit-lsp#1088]
I wonder if there is a support for `textDocument/inlayHint`. It looks like there is because I found this PR:  #465

However, when I try to request data I get:
```
Method not found: textDocument/inlayHint
```

It’s also weird that VS Code somehow is able to get those hints from the LSP.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://123555008

**Comment by adam-fowler** [comment]
In VSCode if you set the setting `swift.sourcekit-lsp.server.trace` to `verbose` you can see all the communication between the VSCode LSP client and SourceKit-LSP in the SourceKit-LSP output pane. Useful for debugging requests. Search for InlayHint and you should see the requests.
