### ISSUE TITLE
`workspace/tests` and `document/tests` are not included in list of capabilities returned at initialization

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#1098]
SourceKit-LSP should report whether it supports test discovery.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://123771703

**Comment by ahoppen** [comment]
@adam-fowler FYI I’m also renaming `document/tests` to `textDocument/tests` in https://github.com/apple/sourcekit-lsp/pull/1112. Realized that we weren’t consistent with other LSP requests here.

**Comment by adam-fowler** [comment]
Cool. I've found I only needed the workspace request. It gets run after every build. Between builds I use the document symbols request to apply edits.
