### ISSUE TITLE
Diagnostics are not refreshed after build when a new file is added

### ISSUE THREAD

**Issue by wojciech-kulik** [apple/sourcekit-lsp#1116]
Steps to reproduce:
1. Add a new file with some class.
2. Reference this class within the same target.
3. Build the project using `xcodebuild` command.

Actual result:
The build succeeds, LSP doesn't print any errors in the log, LSP still shows issues:
<img width="1691" alt="image" src="https://github.com/apple/sourcekit-lsp/assets/3128467/524450ae-55ff-4312-9151-4dc3b5e67016">

Expected result:
LSP should be automatically refreshed and errors should disappear.

Workaround:
Restart LSP (in Neovim `:LspRestart`).

Version:
Sourcekit-lsp provided by Xcode Version 15.2 (15C500b)

Related issue:
https://github.com/wojciech-kulik/xcodebuild.nvim/issues/56

Notes:
I reproduced it both in Neovim and Visual Studio Code, so I guess it's not the LSP client's fault.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://123971779
