### ISSUE TITLE
`workspace/tests` request does not return swift-testing tests 

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#1119]
Also symbol information is probably not enough information for each test. The following additional information would be useful
- source: Did test come from xctest or swift-testing
- label: swift-testing tests can have a label, displaying this in the UI would be good.

swift-testing tests can have a whole bunch more data attached to them but I'm not sure at this time if it is needed. It can always be added at a later date.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://124058880
