### ISSUE TITLE
Conditional compile directives (`#if`) should support code folding

### ISSUE THREAD

**Issue by z2oh** [apple/sourcekit-lsp#1182]
I suspect this probably isn't too hard to implement with another case in [`FoldingRangeFinder`](https://github.com/apple/sourcekit-lsp/blob/63171abcea95f5283be34548634a62c500a1517c/Sources/SourceKitLSP/Swift/FoldingRange.swift#L17).

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://126647384
