### ISSUE TITLE
Errors using @_extern and @_expose in Visual Studio Code

### ISSUE THREAD

**Issue by svanimpe** [apple/sourcekit-lsp#1202]
I'm using swift-6.0-DEVELOPMENT-SNAPSHOT-2024-04-22-a. The following code compiles fine, but keeps showing errors in Visual Studio Code:

<img width="719" alt="Screenshot 2024-04-24 at 13 11 40" src="https://github.com/apple/sourcekit-lsp/assets/1496250/2024fc0f-915b-47f6-9e67-e6422f25635a">

<img width="531" alt="Screenshot 2024-04-24 at 13 11 18" src="https://github.com/apple/sourcekit-lsp/assets/1496250/09a5fc29-c119-400f-a2bd-2f1f9c39a469">

Is there a way to get rid of these?

In the Swift output window, I can see the following:

```
13:12:51: SourceKit-LSP setup
13:12:51: Apple Swift version 6.0-dev (LLVM 94447cf359772fc, Swift f36098a14a0d48b)
```

so I assume VS Code is using SourceKit-LSP from the correct toolchain?

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://126985100

**Comment by ahoppen** [comment]
Interesting, I was not able to reproduce the issue. To figure out what’s going on here, could you 
- Share the settings in your `settings.json` (or at least the settings starting with `swift.`)
- If you are seeing this on macOS (screenshots look like it), could you run `/LibraryDeveloper/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-04-22-a/usr/bin/sourcekit-lsp diagnose` and attach the folder it produces?

**Comment by svanimpe** [comment]
I didn't configure anything in the extension yet. I was using the `TOOLCHAINS` method described here to set my toolchain: https://www.swift.org/install/macos/#installation-via-swiftorg-package-installer

This seemed to work in VS Code as well because of the reported version in the Swift output window. However, today I noticed that some commands (such as package resolution) were still using the Xcode toolchain.

If I set my **Swift: Path** explicitly in VS Code, the errors disappear.

**Comment by ahoppen** [comment]
Yes, setting the `Swift: Path` in the VS Code extension to the downloaded toolchain is the correct way to go. As you noticed, VS Code will otherwise pick up your Xcode toolchain, because VS Code isn’t launched with the `TOOLCHAINS` environment variable.
