### ISSUE TITLE
Symbol completion for Package.swift from SwiftPM project in a subfolder doesn't work

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#1210]
If you have a SwiftPM project in a subfolder of a VSCode workspace, SourceKit-LSP does not provide symbol completion, hover documentation for the Package.swift file even though a `workspace/didChangeWorkspaceFolders` request that adds the subfolder has been sent.

See https://github.com/swift-server/vscode-swift/issues/768

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://127351614

**Comment by svanimpe** [comment]
I'm not sure if this is related, but in one of my projects, I keep getting a  "No such module" error from SourceKit in a regular file, not **Package.Swift**. One of the Code Helper processes also spins up to 100% CPU.

This is using a 6.0 snapshot. With 5.9, everything is fine.

**Comment by ahoppen** [comment]
> I'm not sure if this is related, but in one of my projects, I keep getting a "No such module" error from SourceKit in a regular file, not **Package.Swift**. One of the Code Helper processes also spins up to 100% CPU.
> 
> This is using a 6.0 snapshot. With 5.9, everything is fine.

Could you file a separate issue for this? It seems like a different issue to me. Some initial thoughts:

Did you build your project with the Swift 6.0 snapshot as well? If you build your project using a different toolchain than the one that contains your sourcekit-lsp, SourceKit isn’t able to read your Swift modules, which might cause the issue.

**Comment by svanimpe** [comment]
@ahoppen I've opened #1223
