### ISSUE TITLE
SourceKit is using 100% CPU

### ISSUE THREAD

**Issue by svanimpe** [apple/sourcekit-lsp#1223]
Every time I open the attached project in VS Code, a "Code Helper" process spins up and uses 100% CPU. I suspect this is related to SourceKit, because when I force-quit this process, I can see SourceKit resetting in VS Code.

I've been having a lot of issues with SourceKit over the past few days. I though this was due to me using a 6.0 snapshot, but I've been unable to get rid of this specific issue. It occurs even with 5.9.2, and also with some other projects.

[Project.zip](https://github.com/apple/sourcekit-lsp/files/15210417/Project.zip)

I'm using VS Code 1.89.0 with Swift plugin 1.9.0 with no adjusted settings.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://127546606

**Comment by ahoppen** [comment]
Which OS are you using SourceKit-LSP on?

**Comment by svanimpe** [comment]
macOS 13.6

Since this issue has been blocking me for a few days, I decided to recreate the projects that were affected by it. So far, the issue hasn't reappeared again. I suspect it was the result of me working on 5.9 and 6.0 projects at the same time, but I'm not sure what caused it.

I've tried to resolve it by making sure my `Swift: Path` in VS Code was set to the same toolchain used to build the project, removing the `.build` directory and rebuilding from scratch, cleaning the VS Code cache, etc, with no success.

Feel free to close the issue if the attached project doesn't reproduce it. Should it pop up again, I'll leave a comment here, and try to gather more diagnostics.

**Comment by ahoppen** [comment]
Closing this issue as this is not an issue with VS Code itself. If you see the issue again, could you file an issue to the Swift VS Code extension at https://github.com/swift-server/vscode-swift/issues and a attache a profile as described in https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions? It could also be another, unrelated extension that’s utilizing the CPU at 100%, the profile should be able to tell.
