### ISSUE TITLE
Add requests to pause and resume indexing 

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#1304]
### Description

When I run a build in Xcode it pauses indexing is it worthwhile providing support for this in SourceKit-LSP?

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://128149559

**Comment by ahoppen** [comment]
Unless a compelling use for it comes up, I would prefer to not pause indexing automatically in SourceKit-LSP. Especially with https://github.com/apple/sourcekit-lsp/issues/1260, indexing shouldn’t compete with the running processes for system resources.

**Comment by adam-fowler** [comment]
I guess as long as it doesn't slowdown or interrupt builds that'll be fine. But at the moment Xcode pauses indexing when building.

**Comment by ahoppen** [comment]
Oh, I see, you meant while building, I caught on to the *run* part of your description. 

Xcode has index while building, so a build does index your project as well, so it doesn’t make sense to run a background index simultaneously. In SourceKit-LSP, you currently either purely use index-while-building (status quo) or background indexing (what I’ve been implementing recently) and there’s no way to merge the two. The exact details of how to achieve that (and if we want to at all) are still TBD (https://github.com/apple/sourcekit-lsp/issues/1270 has some of the challenges) and until we do that, there’s no reason to pause indexing during a build.
