### ISSUE TITLE
swift tools URL from README responds with 404 

### ISSUE THREAD

**Issue by kristoferfannar** [apple/sourcekit-lsp#1446]
### Swift version

N/A

### Platform

N/A

### Editor

N/A

### Does the issue reproduce with Swift 6?

Yes

### Description

In the repository's README, in the getting started section, it seems to me that the URL provided, https://www.swift.org/tools, points towards a 404 page. 

I've tried to query the URL on two different IPs, using both a browser and curl, and at two times during today, but still get the 404 result.

### Steps to Reproduce

open https://www.swift.org/tools in your browser. 
I'm querying from Iceland and am being directed to 17.253.63.203.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://129367728

**Comment by kristoferfannar** [comment]
I see that this URL was added in b332f3d, just two days ago, which I find confusing. 
My best bet is that you're expecting swift.org/tools to exist soon?
