### ISSUE TITLE
Add an identifier to work done progress messages

### ISSUE THREAD

**Issue by plemarquand** [apple/sourcekit-lsp#1476]
### Description

[Work done progress messages](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#progress) (`$/progress`) contain a `message` and a `title`, but there is no `id` to match begin/end events up together. It is possible to use the title, but if developers want to check for specific types of work progress they'll have to key off the title and if that title ever changes in future then their code will break.

It would be nice to add an `id` field to these progress messages that is considered immutable. One catch is there is no `id` field in the [protocol definition](https://github.com/microsoft/vscode-languageserver-node/blob/1ce790dd341a38da1fbf902cddc16ce456149de0/protocol/src/common/protocol.progress.ts#L11) so this would be out of spec.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://129678779

**Comment by ahoppen** [comment]
Adding a consistent prefix to the token of the work done progress here: https://github.com/apple/sourcekit-lsp/pull/1493

For crashed sourcekitd, this will be `sourcekitd-crashed`.
