### ISSUE TITLE
Add missing protocol requirements placeholders not replaced

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#480]
The add missing protocol requirements placeholders are not replaced with LSP snippets. The output is as follows
```
func missingRequirement() {
    <#code#>
}
```
Original bug came from vscode-swift extension https://github.com/swift-server/vscode-swift/issues/269
I believe there is already a radar for this, but wanted to add an issue here so it can be tracked externally.

Swift version: swift-driver version: 1.45.2 Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
Target: x86_64-apple-macosx12.0

**Comment by ahoppen** [comment]
Fixed by https://github.com/apple/sourcekit-lsp/pull/481.
