### ISSUE TITLE
[SR-15918] Sourcekit-LSP reverts swift package edit

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#501]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15918      |
   |Radar             | rdar://89551074         |
   |Original Reporter | @adam-fowler      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Apple Swift version 5.6-dev (LLVM 62b900d3d0d5be9, Swift ce64fe8867792d4)  
vscode extension v0.3.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SourceKit-LSP    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 09b4fc6b8bc8b6b62a4ce159b0ab11b5

  </details>

**Issue Description:**

5.6 version of sourcekit-lsp reverts any attempt at local editing of packages. This was replicated using vscode extension.

-   Run vscode with 5.6 version of toolchain

-   Open project

-   Open .build/workspace-state.json

-   Right click on dependency and select 'Use Local Version' and select local version of a dependency

-   Watch workspace-state.json change to include edited state of dependency and then watch it revert back to non-edited almost immediately.

The revert does not occur if I stop the sourcekit-lsp server

**Comment by ahoppen** [comment]
Fixed in SwiftPM by https://github.com/apple/swift-package-manager/pull/5510.
