### ISSUE TITLE
[SR-15875] SourceKit-LSP: Locally edited modules are ignored

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#504]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15875      |
   |Radar             | rdar://89082936         |
   |Original Reporter | @adam-fowler      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)

Target: x86_64-apple-macosx12.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SourceKit-LSP    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 9855defbb99208c70a8c938d34e6f625

  </details>

**Issue Description:**

If I locally edit a module from a package using \`swift package edit\` SourceKit-LSP ignores the local version and continues to use the original version of the module.

I know \`swift package edit\` is being deprecated, but there will be a replacement for it and it would be good if SourceKit-LSP worked for that. It may be worthwhile talking to SPM team to find out if the new solution will still use \`workspace-state.json\` to store module state.

**Comment by ahoppen** [comment]
Same underlying issue as #501
