### ISSUE TITLE
[SR-13763] SourceKit-LSP should provide a better error when a "notification" is sent as a "request"

### ISSUE THREAD

**Issue by benlangmuir** [apple/sourcekit-lsp#528]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13763      |
   |Radar             | rdar://problem/70546466         |
   |Original Reporter | @benlangmuir      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SourceKit-LSP    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: eeb6e0002ae127c14c5a2f79b3cf1187

  </details>

**Issue Description:**

If a client incorrectly sends a notification message with a request id, we currently send the response "method not found: \<method name\>".

We should improve this error by checking if the method is a known notification so that it is clear what the issue is. E.g.

"\<method name\> is a notification message, but received as a request"

**Comment by ahoppen** [comment]
Having worked on sourcekit-lsp for a year now, this never turned out to be an issue. Let’s close it.
