### ISSUE TITLE
[SR-13762] SourceKit-LSP textDocument/* requests return no results if document is not open

### ISSUE THREAD

**Issue by benlangmuir** [apple/sourcekit-lsp#529]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13762      |
   |Radar             | rdar://problem/70546468         |
   |Original Reporter | @benlangmuir      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SourceKit-LSP    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 90305bde26b3949654dd517a12e74963

  </details>

**Issue Description:**

The `"textDocument/*"` requests such as completion, definition, references, documentSymbol, etc. will return a fallback value (e.g. `[]` for completion, `nil` for documentSymbol) when they are called on a document that has not been opened.

We should improve these to either return an error indicating what went wrong, or else support it by opening the file from disk.

**Comment by ahoppen** [comment]
These methods should all return an error now instead of the fallback result.
