### ISSUE TITLE
[SR-13145] Add '(' to the trigger characters for code completion

### ISSUE THREAD

**Issue by swift-ci** [apple/sourcekit-lsp#532]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13145      |
   |Radar             | None         |
   |Original Reporter | srinikhil07 (JIRA User)      |
   |Type              | Improvement    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963880-738a5bc8-061e-4988-a0d6-faeb00198ae6.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | CodeCompletion, SourceKit-LSP    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c766dd4b8f3f8aba0394fcdd22896d51

  </details>

**Issue Description:**

**Toolchain:**

I am using sourcekit-lsp bundled in Xcode-12 beta 1 on macOS 10.15.5 and my editor is VSCode.

**Improvement:**

When I type the below in both Xcode and VSCode, I get different results.

``` java
 var array = Array(
```

For Xcode, I get the perfect code completion as shown below,

![image-2020-07-05-15-23-53-078](https://user-images.githubusercontent.com/4062178/174825727-6955e13f-8350-4e63-93a2-9a2227120db8.png)

But the same in VSCode, I get empty result.

![image-2020-07-05-15-24-39-422](https://user-images.githubusercontent.com/4062178/174825758-42c56489-215f-4e48-8d96-b83c155779a7.png)

I am not sure if Xcode 12 uses sourcekit-lsp for code completion. But it would be awesome if we get same level of richness in VSCode as well.

 

I would love to contribute for this improvement.

**Comment by ahoppen** [comment]
rdar://95597383

**Comment by ahoppen** [comment]
I just thought about this again and there doesn’t appear to be a good solution in LSP. All we could do is add `(` to the trigger characters but I believe that the regression when writing tuples or parenthesized expressions will be worse than the improvement for function calls. So, I’m closing this.
