### ISSUE TITLE
[SR-12735] sourcekit-lsp doesn't handle headings correctly in hover response

### ISSUE THREAD

**Issue by swift-ci** [apple/sourcekit-lsp#534]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12735      |
   |Radar             | rdar://problem/62895105         |
   |Original Reporter | cukier (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963779-968632de-8f26-48dd-94d2-b5ebd5395c2c.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SourceKit-LSP    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 2aca529ac78bd7e234ac3341b255ac12

  </details>

**Issue Description:**

If you have a function with doc comment that includes headings, they are rendered with literal \<h1\> tags around them, instead of being bigger and boldier. 

 

I did some debugging, and it seems that sourcekit returns headings as \`\<rawHTML\>\<!\[CDATA\[\<h1\>\]\]\>\</rawHTML\>two\<rawHTML\>\<!\[CDATA\[\</h1\>\]\]\>\</rawHTML\>\` instead of \`\<h1\>two\</h1\>\` that sourcekit-lsp expects

 

(sorry for the weird font, line 10 contains three equals characters "===")

![](Screen Shot 2020-05-05 at 3.24.26 PM.png)

**Comment by ahoppen** [comment]
I wasn’t able to reproduce the issue. Closing.
