### ISSUE TITLE
[SR-12491] Create a branch of sourcekit-lsp setup with the latest released Swift toolchain

### ISSUE THREAD

**Issue by benlangmuir** [apple/sourcekit-lsp#536]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12491      |
   |Radar             | rdar://problem/62201105         |
   |Original Reporter | @benlangmuir      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SourceKit-LSP    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 7be0189d3ec7cd413edbff041349f37e

  </details>

**Issue Description:**

It would be useful to have a branch (e.g. `master-with-swift-5.2`) that contains the latest changes to sourcekit-lsp, but built to work with the currently released swift-5.2 toolchain. Currently we only have master (which works with master swift/swiftpm) and swift-5.2-branch (which works with swift-5.2, but does not receive new changes since it is already released).

Specifics

-   Create a branch `master-with-swift-5.2` that uses master sourcekit-lsp, but swiftpm from 5.2.

-   Add PR testing for this branch that uses the latest released toolchain. This could be simpler than the existing PR testing and just use the downloadable toolchain instead of build swift from source.

-   Add a gated automerger from `master` to `master-with-swift-5.2` if it tests successfully.

-   When we release swift-5.3, end support for 5.2 and move to `master-with-5.3`.

**Comment by ahoppen** [comment]
Since the requirement for this never really came up in the last couple of years, I’m going to close this. AFAICT the current `main` SourceKit-LSP builds with the last resealed Swift toolchain.
