### ISSUE TITLE
[SR-12378] SKTests.testDependenciesUpdatedCXXTibs - Fatal error: error timedOut waiting for post-build diagnostics notification: file SourceKitTests.swift, line 284

### ISSUE THREAD

**Issue by benlangmuir** [apple/sourcekit-lsp#538]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12378      |
   |Radar             | rdar://95598365         |
   |Original Reporter | @benlangmuir      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SourceKit-LSP    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: bbf17e241120bcbef3aa7759eeea981e

  </details>

**Issue Description:**

<https://ci.swift.org/job/swift-PR-Linux-smoke-test/20969>

    13:07:17 Test Case 'SKTests.testDependenciesUpdatedCXXTibs' started at 2020-03-17 20:07:17.947
    13:07:18 I[20:07:18.038] clangd version 7.0.0 (https://github.com/apple/llvm-project.git f12bb53299b8732744cd61826ee38bcefd9597d6)
    13:07:18 I[20:07:18.038] PID: 58040
    13:07:18 I[20:07:18.038] Working directory: /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/sourcekitlsp-linux-x86_64/x86_64-unknown-linux-gnu/release/sk-tests/SKTests.testCodeCompleteSwiftTibs
    13:07:18 I[20:07:18.038] argv[0]: /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift-nightly-install/usr/bin/clangd
    13:07:18 I[20:07:18.038] argv[1]: -compile_args_from=lsp
    13:07:18 I[20:07:18.038] argv[2]: -background-index=false
    13:07:18 I[20:07:18.038] argv[3]: -index=false
    13:07:18 I[20:07:18.038] Starting LSP over stdin/stdout
    13:07:18 I[20:07:18.038] <-- initialize(1)
    13:07:18 I[20:07:18.039] --> reply:initialize(1) 0 ms
    13:07:18 I[20:07:18.041] <-- initialized
    13:07:18 I[20:07:18.041] unhandled notification initialized
    13:07:18 I[20:07:18.043] <-- workspace/didChangeConfiguration
    13:07:18 I[20:07:18.043] <-- textDocument/didOpen
    13:07:18 I[20:07:18.043] Updating file /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/tmp/sk-test-data/SKTests.testDependenciesUpdatedCXXTibs/src/main.c with command 
    13:07:18 [/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/tmp/sk-test-data/SKTests.testDependenciesUpdatedCXXTibs/build]
    13:07:18 /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift-nightly-install/usr/bin/clang -fsyntax-only /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/tmp/sk-test-data/SKTests.testDependenciesUpdatedCXXTibs/src/main.c -I . -I /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/tmp/sk-test-data/SKTests.testDependenciesUpdatedCXXTibs/src -index-store-path index -index-ignore-system-symbols -fmodules -fmodules-cache-path=ModuleCache -o main-main.c.o -resource-dir=/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift-nightly-install/usr/lib/clang/7.0.0
    13:07:18 I[20:07:18.044] <-- workspace/didChangeConfiguration
    13:07:18 I[20:07:18.061] --> textDocument/publishDiagnostics
    13:07:18 I[20:07:18.545] Updating file /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/tmp/sk-test-data/SKTests.testDependenciesUpdatedCXXTibs/src/main.c with command 
    13:07:18 [/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/tmp/sk-test-data/SKTests.testDependenciesUpdatedCXXTibs/build]
    13:07:18 /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift-nightly-install/usr/bin/clang -fsyntax-only /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/tmp/sk-test-data/SKTests.testDependenciesUpdatedCXXTibs/src/main.c -I . -I /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/tmp/sk-test-data/SKTests.testDependenciesUpdatedCXXTibs/src -index-store-path index -index-ignore-system-symbols -fmodules -fmodules-cache-path=ModuleCache -o main-main.c.o -resource-dir=/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift-nightly-install/usr/lib/clang/7.0.0
    13:07:18 I[20:07:18.561] --> textDocument/publishDiagnostics
    13:07:18 I[20:07:18.601] <-- textDocument/didChange
    13:07:19 I[20:07:19.102] Updating file /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/tmp/sk-test-data/SKTests.testDependenciesUpdatedCXXTibs/src/main.c with command 
    13:07:19 [/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/tmp/sk-test-data/SKTests.testDependenciesUpdatedCXXTibs/build]
    13:07:19 /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift-nightly-install/usr/bin/clang -fsyntax-only /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/tmp/sk-test-data/SKTests.testDependenciesUpdatedCXXTibs/src/main.c -I . -I /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/tmp/sk-test-data/SKTests.testDependenciesUpdatedCXXTibs/src -index-store-path index -index-ignore-system-symbols -fmodules -fmodules-cache-path=ModuleCache -o main-main.c.o -resource-dir=/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift-nightly-install/usr/lib/clang/7.0.0
    13:07:19 I[20:07:19.104] Skipping rebuild of the AST for /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/tmp/sk-test-data/SKTests.testDependenciesUpdatedCXXTibs/src/main.c, inputs are the same.
    13:07:21 Fatal error: error timedOut waiting for post-build diagnostics notification: file /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/sourcekit-lsp/Tests/SourceKitTests/SourceKitTests.swift, line 284
    13:07:21 E[20:07:21.768] Transport error: Input/output error
    13:07:21 I[20:07:21.768] LSP finished, exiting with status 1
    13:07:21 E[20:07:21.768] Transport error: Input/output error
    13:07:21 I[20:07:21.768] LSP finished, exiting with status 1
    13:07:21 E[20:07:21.768] Transport error: Input/output error
    13:07:21 I[20:07:21.768] LSP finished, exiting with status 1
    13:07:21 E[20:07:21.768] Transport error: Input/output error
    13:07:21 I[20:07:21.768] LSP finished, exiting with status 1
    13:07:21 E[20:07:21.768] Transport error: Input/output error
    13:07:21 I[20:07:21.768] LSP finished, exiting with status 1
    13:07:21 E[20:07:21.769] Transport error: Input/output error
    13:07:21 I[20:07:21.769] LSP finished, exiting with status 1
    13:07:21 E[20:07:21.770] Transport error: Input/output error
    13:07:21 I[20:07:21.770] LSP finished, exiting with status 1
    13:07:21 Exited with signal code 4

**Comment by ahoppen** [comment]
Re-enabled the test here: https://github.com/apple/sourcekit-lsp/pull/574
