### ISSUE TITLE
Multi-workspace: Sourcekit-LSP can use the wrong workspace if one is inside another.

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#557]
VSCode automatically adds workspace folders to the LSP server (sends `workspace/didChangeWorkspaceFolders` notification) for all workspace folders added to VSCode. If the VSCode workspace folder has subfolders that contain packages when these subfolders are added to the LSP server, they are ignored because SourceKit-LSP will always choose the workspace root folder, over the subfolder (because it was added first).

This causes an issue in the following example. Below is a example workspace structure. We have a `RootFolder` without a `Package.swift` and then we have two subfolders that both contain SwiftPM packages.

```
- RootFolder
  - folder1
    - Package.swift
    - ...
  - folder2
    - Package.swift
    - ...
```

When we load this project, VSCode automatically adds `RootFolder` as a LSP workspace folder. When we go to open either `folder1` or `folder2` the vscode-swift extension will then add that folder as a LSP workspace folder, but as indicated above SourceKit-LSP will ignore the subfolder because `RootFolder` takes precedence even though it doesn't hold a `Package.swift`. Could we get SourceKit-LSP to prioritise workspace folders that hold a Package.swift over folders that don't.

**Comment by ahoppen** [comment]
rdar://94026341

**Comment by ahoppen** [comment]
Fixed by https://github.com/apple/sourcekit-lsp/pull/558
