### ISSUE TITLE
Need help with Package.swift

### ISSUE THREAD

**Issue by xbladesub** [apple/sourcekit-lsp#569]
I have big iOS project which uses cocoapods. I want to be able to work on this project using neovim. 

Is it possible to tell ```sourcekit-lsp``` somehow to detect existing Xcode build so I don't have to run 'swift build' and create Package.swift in root of the project? (some of these libraries are only in cocoapods variant - no SPM)

**Comment by ahoppen** [comment]
If I understand correctly, what you are asking is that SourceKit-LSP should support opening Xcode projects, right? 

Opening Xcode projects in SourceKit-LSP is not something we support. There has been some discussion around this in the Forums, which also list some workarounds that you might want to try:
- https://forums.swift.org/t/xcode-project-support/20927
- https://forums.swift.org/t/whats-the-plan-for-index/18441

**Comment by xbladesub** [comment]
> If I understand correctly, what you are asking is that SourceKit-LSP should support opening Xcode projects, right?
> 
> Opening Xcode projects in SourceKit-LSP is not something we support. There has been some discussion around this in the Forums, which also list some workarounds that you might want to try:
> 
> * https://forums.swift.org/t/xcode-project-support/20927
> * https://forums.swift.org/t/whats-the-plan-for-index/18441

thanks, but all this is about how to escape Xcode and use SourceKit-LSP with neovim (I mean develop iOS apps, without returning to Xcode)

**Comment by ahoppen** [comment]
If you manage to describe the entire build process of your iOS app using SwiftPM, you will be able to use SourceKit-LSP just fine. To the best of my knowledge this is not currently possible because SwiftPM doesn’t know how to bundle up iOS apps – but I might be wrong here. In that case you still need an Xcode project to deploy the app to your phone.

**Comment by ahoppen** [comment]
I’m closing this because support Xcode projects in SourceKit-LSP is not something we are planning to support in the near future with the rationale mentioned in this [Forums Thread](https://forums.swift.org/t/whats-the-plan-for-index/18441/4):

> There is no officially supported way to understand Xcode projects outside of Xcode, for example there is nothing like libSwiftPM which the SwiftPM team commits to support as a way of understanding SwiftPM projects. Unless this situation changes, we do not intend to support Xcode projects outside of the Xcode IDE. Xcode itself will change to provide its settings directly to sourcekit-lsp, when used from inside the IDE.
> 
> People have devised methods for getting a compilation database out of an Xcode project, you may want to look into these, the compilation database is something we intend to maintain first-class support for.
