### ISSUE TITLE
semantic highlighter labels `await` as an identifier

### ISSUE THREAD

**Issue by kelvin13** [apple/sourcekit-lsp#591]
the semantic highlighter seems to think `await` is an identifier, and not a (contextual) keyword.

![Screenshot from 2022-07-17 21-30-55](https://user-images.githubusercontent.com/2556986/179601034-28da646b-435b-4688-a3c3-f67c7612e051.png)

because sourcekit-lsp provides a classification (`identifier`) for `await`, instead of leaving it unclassified, this means it is [not possible to override the highlight in vscode](https://stackoverflow.com/questions/65927861/how-to-override-semantic-token-type-of-vscode-theme).

**Comment by kelvin13** [comment]
this *might* be related to modifiers being dropped from:

https://github.com/apple/sourcekit-lsp/blob/main/Sources/SourceKitLSP/Swift/SyntaxHighlightingToken.swift#L161

if there is more than one bit set at a time.

**Comment by ahoppen** [comment]
Which version of sourcekit-lsp are you using? `await` is highlighted correctly in recent the swift-DEVELOPMENT-SNAPSHOT-2022-06-16-a development snapshot for the following Swift file

```swift
func foo() async {}

func test() async {
  await foo()
}
```

**Comment by kelvin13** [comment]
on `DEVELOPMENT-SNAPSHOT-2022-07-06-a`, it is **not** highlighted correctly, when semantic highlighting is enabled:

![Screenshot from 2022-07-21 14-10-02](https://user-images.githubusercontent.com/2556986/180297346-b4521bc7-44e5-4dd3-bd1f-c1945349d81f.png)

if semantic highlighting is disabled, the fallback grammar comes into effect and `await` is highlighted correctly (but other syntax is no longer highlighted correctly.)

![Screenshot from 2022-07-21 14-10-34](https://user-images.githubusercontent.com/2556986/180297496-340d6ae7-86c7-4dc3-84d9-4c957a4624c3.png)

semantic highlighting is disabled by default in the swift vscode plugin, which is likely why there is less awareness of this issue.

**Comment by kelvin13** [comment]
related issue: https://github.com/swift-server/vscode-swift/issues/366

**Comment by ahoppen** [comment]
I just tried this as well and `await` is correctly highlighted for me with swift-DEVELOPMENT-SNAPSHOT-2022-07-18-a.

<img width="792" alt="Screenshot 2022-07-21 at 23 29 57" src="https://user-images.githubusercontent.com/4062178/180318567-d49b2506-c5ba-44c1-ac3a-c899408e6915.png">

I don’t see any option to enable or disable semantic highlighting in the VSCode plugin. How do you enabled/disable it?

Also: How did you open the debug panels showing in your screenshots?

**Comment by kelvin13** [comment]
to enable semantic highlighting, set the `editor.semanticHighlighting.enabled` option to `true`, or use a syntax theme (like [swift-madrid](https://github.com/kelvin13/vs-swift-madrid-theme)) that overrides the default setting.

see: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

to activate the token inspector, Ctrl-Shift-P and select the **Developer: Inspect Editor Tokens and Scopes** command

**Comment by kelvin13** [comment]
can confirm this is fixed in `DEVELOPMENT-SNAPSHOT-2022-08-01-a`. this was driving me nuts, thank you @ahoppen !
