### ISSUE TITLE
operator and operator lexeme declarations should be highlighted as identifiers

### ISSUE THREAD

**Issue by kelvin13** [apple/sourcekit-lsp#595]
> note: this issue was split off from https://github.com/swift-server/vscode-swift/issues/366

**Describe the bug**

operator lexeme declarations should be highlighted as identifiers.

```
infix operator ?= :ComparisonPrecedence
```

![Screenshot from 2022-07-22 14-20-47](https://user-images.githubusercontent.com/2556986/180511786-2546fecf-a4e2-458c-b462-c047f4d17a12.png)

there are **three** bugs here. two are vscode-swift bugs, and the other one is a sourcekit-lsp bug:

| lexeme | `?=` | `:` | `ComparisonPrecedence` |
| --- |  --- | --- | --- |
| current semantic highlight | none | none | `identifier` |
| expected semantic highlight | `identifier` | none | `identifier` |
| sourcekit-lsp bug? | **yes** | no | no |
| current fallback label | `operator` | `invalid` | `invalid` |
| expected fallback label | `operator` | none | none |
| [vscode](https://github.com/microsoft/vscode/blob/main/extensions/swift/syntaxes/swift.tmLanguage.json) bug? | no | **yes** | **yes**<sup>[1]</sup> |

> [1]: has no effect, because the correct sourcekit-lsp highlight overrides the wrong fallback label)

the wrong highlight for the colon is a vscode problem, and probably not in our power to fix. the only way to correct this behavior would be to make sourcekit-lsp provide more comprehensive highlights (classifying punctuation and identifiers in a way it does not do currently) and migrate the community to swift-specific syntax coloring themes that do not suffer from this defect. however, the operator lexeme highlight *is* within our power to fix.

this also seems to affect operator declarations, but the impact is mitigated because the fallback grammar is able to fill in for the semantic highlighter in this case.

![Screenshot from 2022-07-22 14-21-07](https://user-images.githubusercontent.com/2556986/180512191-9b3da3ff-842e-435d-a042-04245edee8b5.png)

**Environment**
 - OS: Ubuntu 20.04
 - vscode-swift version: 0.6.0
 
```
$ swift --version
Swift version 5.8-dev (LLVM 396c6969ee90ef4, Swift 02efc3a2d28e348)
Target: x86_64-unknown-linux-gnu
$ swiftenv version
DEVELOPMENT-SNAPSHOT-2022-07-06-a 
$ code --version
1.69.2
3b889b090b5ad5793f524b5d1d39fda662b96a2a
x64
```

**Comment by ahoppen** [comment]
I don’t think I agree `?=` should be highlighted as an identifier, because it is not an identifier – it’s an operator. https://docs.swift.org/swift-book/ReferenceManual/LexicalStructure.html#ID412

Why do you think it should be highlighted as an identifier?

**Comment by kelvin13** [comment]
as far as i’m aware, there is no such thing as an “operator” in the semantic highlights sourcekit-lsp emits. currently operator-functions like `+=` or `...` are labeled as `method.static`, which they are. 

it’s not really important to me whether they are called *operators* or *identifiers*, the problem is right now they are not getting any semantic highlights at all.

**Comment by ahoppen** [comment]
Implementing the SourceKit-side here: https://github.com/apple/swift/pull/60210 This will need to be adopted in SourceKit-LSP in a follow-up PR.

**Comment by ahoppen** [comment]
rdar://97961816
