### ISSUE TITLE
nil should still be highlighted as a keyword in a case pattern

### ISSUE THREAD

**Issue by kelvin13** [apple/sourcekit-lsp#599]
`nil` is highlighted as a keyword everywhere except when it is being pattern-matched in a case pattern (`switch`, `if case`, etc.)

![Screenshot from 2022-07-29 14-08-01](https://user-images.githubusercontent.com/2556986/181828366-5676cc5f-dc32-445b-ad66-6d9e16f0c3f8.png)

this is *technically* correct, but makes for some strange highlighting in a text editor. it would be better if `nil` was the same color everywhere.

**Comment by ahoppen** [comment]
rdar://97961865
