### ISSUE TITLE
crash: typing a string interpolation anchor instantly crashes sourcekit-lsp

### ISSUE THREAD

**Issue by kelvin13** [apple/sourcekit-lsp#607]
opening the following SPM test project in vscode instantly crashes sourcekit-lsp:

[sourcekit-lsp-crash-3.zip](https://github.com/apple/sourcekit-lsp/files/9275811/sourcekit-lsp-crash-3.zip)

```swift
public struct sourcekit_lsp_crash_3 {
    var description:String 
    {
        """
        \()
        """
    }
}
```

```
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
[Info  - 4:56:02 PM] Connection to server got closed. Server will restart.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
[Info  - 4:56:02 PM] Connection to server got closed. Server will restart.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
[Info  - 4:56:03 PM] Connection to server got closed. Server will restart.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
[Info  - 4:56:03 PM] Connection to server got closed. Server will restart.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
[Error - 4:56:04 PM] The SourceKit Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

vscode-swift-extension: v0.6.0

```
$ swiftenv version
DEVELOPMENT-SNAPSHOT-2022-08-01-a 
$ swift --version
Swift version 5.8-dev (LLVM 07d14852a049e40, Swift 613b3223d9ec5f6)
Target: x86_64-unknown-linux-gnu
$ code --version
1.69.2
3b889b090b5ad5793f524b5d1d39fda662b96a2a
x64
```

**Comment by ahoppen** [comment]
rdar://98304976

**Comment by ahoppen** [comment]
I just tried reproducing this and SourceKit-LSP isn’t crashing for me if I perform the following steps:
- Open the attached project
- Type `test` inside the parentheses of the string interpolation in sourcekit_lsp_crash_3.swift

Are there any other steps you perform to make SourceKit-LSP crash?

**Comment by kelvin13** [comment]
if you type `test` inside the parentheses quickly enough, it will not crash, because the string interpolation anchor only crashes when it is empty. 

if you leave the parentheses empty, it blinks 3 times, and then crashes.

**Comment by DavidGoldman** [comment]
I believe this should have been fixed by https://github.com/apple/sourcekit-lsp/pull/602

**Comment by ahoppen** [comment]
@kelvin13 Could you check if you are still seeing the issue with the most recent swift development snapshot?

**Comment by kelvin13** [comment]
yep, this has been fixed! thank you!!
