### ISSUE TITLE
Add custom request to return a list of all the tests in a project with locations

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#611]
This is something that would be used by the Visual Studio Code extension to provide location information for tests in the Test Explorer. 

Currently the extension uses the `swift test --list-tests` command to get a list of tests, but this doesn't return locations of the tests. I did add a request https://github.com/apple/swift-package-manager/issues/5601 to add this information to the `--list-tests` output. But it seems it has been decided it would be easier to do this using SourceKit-LSP.

**Comment by ahoppen** [comment]
rdar://98710526
