### ISSUE TITLE
SourceKit (and Xcode) instantly crashes on "/(?<>)/"

### ISSUE THREAD

**Issue by cyanite** [apple/sourcekit-lsp#636]
That's a regex literal with a names capture with an empty name. It doesn't compile, of course, since name is required. This fails correctly. But Xcode instantly crashes when typing it, or when opening any source code containing it.

The top of the stack:

    Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
    0   libswiftCore.dylib            	       0x1b31c4594 _assertionFailure(_:_:file:line:flags:) + 672
    1   libswiftCore.dylib            	       0x1b31c4594 _assertionFailure(_:_:file:line:flags:) + 672
    2   SourceEditor                  	       0x127c8509c SourceEditorLanguageService.enumerateSyntaxTokensOnLine(_:handler:) + 368
    3   SymbolCacheSupport            	       0x126219c54 protocol witness for SourceEditorLanguageService.enumerateSyntaxTokensOnLine(_:handler:) in conformance SymbolCacheLanguageService + 100
    4   SourceEditor                  	       0x127c2e498 SourceEditorLayoutManager.unprocessedLineRenderData(for:context:) + 2520

**Comment by cyanite** [comment]
The scenario: Let me write a regex; I need a capture, I'll find a name later... oh..

**Comment by ahoppen** [comment]
rdar://100185000

**Comment by benlangmuir** [comment]
This crash appears to be in Xcode, not in sourcekit or sourcekit-lsp.

**Comment by cyanite** [comment]
Sorry, I wasn't sure how exactly they were connected. I assumes Xcode uses sourcekit to do its language sense.

**Comment by ahoppen** [comment]
This repo is about SourceKit-LSP, which provides semantic functionality for editors like VSCode. The issue you are describing happens inside Xcode, so it’s not part of this project. Could you file a bug report at http://feedbackassistant.apple.com?
