### ISSUE TITLE
sourcekit-lsp not working on *.mm files in Webkit source in VSCode

### ISSUE THREAD

**Issue by blacktop** [apple/sourcekit-lsp#641]
I see in the README this should work on ObjC code and I "assume" ObjC++ ?  However, goto definition etc is not working for me.  I am using the Swift extension mentioned here https://github.com/apple/sourcekit-lsp/tree/main/Editors

Is it that it's not finding `clangd`? I also have the VSCode cpp plugin installed so not sure if they are "fighting" though I believe the Cpp plugin ignores all ObjC files *(the reason I need sourcekit-lsp 😉)

Thanks!

**Comment by ahoppen** [comment]
rdar://100541602

**Comment by adam-fowler** [comment]
I had a look at this on the VSCode side and as long as the `*.mm` files are in a Swift Package they are being sent to SourceKit-LSP.

**Comment by ahoppen** [comment]
As @adam-fowler mentioned, SourceKit-LSP should support Objective-C++. To help us debug what’s going wrong, could you 
- Launch a fresh VSCode instance
- Reproduce the issue
- In VSCode open the Output windows (Command Palette -> Output: Focus on Output View) -> select SourceKit Language Server and attach the logs to this issue

**Comment by blacktop** [comment]
I was trying to get it to work with the Webkit src https://github.com/WebKit/WebKit

I assume it wasn't working because there is no package.swift in the root? What is the minimal contents I would need to add to that file to get the lsp to pickup all the code?

**Comment by ahoppen** [comment]
Oh, that’s quite a large project. I think adding a `Package.swift` for that will be difficult but maybe the WebKit build system can produce [`compile_commands.json`](https://clang.llvm.org/docs/JSONCompilationDatabase.html) which VSCode also understands.

**Comment by ahoppen** [comment]
AFAICT there’s nothing actionable for sourcekit-lsp here, so I’m closing the issue. Feel free to re-open it if you believe there’s a SourceKit-LSP issue that needs to be fixed.
