### ISSUE TITLE
File opened by SK-LSP in exclusive mode again

### ISSUE THREAD

**Issue by compnerd** [apple/sourcekit-lsp#644]
It seems that we have regressed over the last ~month where I am now seeing source files being opened by SourceKit-LSP in exclusive mode, preventing others from modifying the file while being monitored by the LSP.  This prevents the use of the LSP from VSCode as modifications cannot be saved.  This was previously encountered and fixed, though I do not remember where/what the change was to release the file from the LSP.

CC: @ahoppen @bnbarham

**Comment by ahoppen** [comment]
rdar://100710637

**Comment by ahoppen** [comment]
I suspect that sourcekitd is what’s opening the file in exclusive mode but I don’t have any recollection what we did to fix the issue last time. Do you have any means to monitor on Windows where that file got opened in exclusive mode?

**Comment by compnerd** [comment]
Hmm, would sourcekitd be opening the `.swift` files?  If so, that seems likely.  I think that is correct though - I don't remember what we did, but it was an open in sourcekitd :/

**Comment by compnerd** [comment]
It seems that there is something else that is going on here.  Some files are writable while others are not.  This implies that either we are opening files with different access dispositions or we are closing files at some point in some cases.  It is yet unclear which scenario I am seeing though.

**Comment by ahoppen** [comment]
Fixed by https://github.com/apple/swift/pull/69573

**Comment by z2oh** [comment]
This has started cropping up for us again.

Interestingly, after we enabled LSP with a CMake build, things appeared to be stable for a few days, and then multiple engineers started reporting this issue daily. There were no changes to the deployed toolchain/sourcekit-lsp in this time, so I'm not sure what would've caused this to reappear. This timeline could be a red herring.

In any event, we are seeing this somewhat frequently. During an instance of the issue, the sourcekit-lsp logs show multiple `textDocument/willSave` notifications coming through without any corresponding `textDocument/didSave` although I imagine this is just a symptom of the underlying issue.

**Comment by ahoppen** [comment]
@tristanlabelle Do you remember how you find the culprit last time? Also @z2oh if you happen to find a workflow that reproduces this issue, that would be helpful.

**Comment by tristanlabelle** [comment]
Yeah, we have a code generator that overrides a bunch of swift files, so it becomes pretty likely that one of them is going to be locked. @z2oh has used this trick and is reproducing it now by using a python script that goes and touch every swift file until it finds one that's locked.

But I'm not sure I had correlated it with the code I fixed it (by avoiding memory mapping), I think it was more anecdotal that we were seeing fewer locked files after that.

**Comment by z2oh** [comment]
In case it is useful, here's the aforementioned python script I'm using to repro this:

<details>
  <summary>Python script</summary>

  ```python
  import time
  import random
  import os
  import heapq
  import string
  import sys
  
  root_path = 'C:\\path\\to\\swift\\project'
  
  def generate_random_string(length):
      # Define the characters to choose from
      characters = string.ascii_letters + string.digits + string.punctuation
  
      # Generate the random string
      random_string = ''.join(random.choice(characters) for _ in range(length))
  
      return random_string
  
  class PriorityQueue:
      def __init__(self):
          self._queue = []
          self._index = 0
  
      def push(self, item, priority):
          heapq.heappush(self._queue, (priority, self._index, item))
          self._index += 1
  
      def pop(self):
          return heapq.heappop(self._queue)[-1]
  
      def peek(self):
          return self._queue[0]
  
      def len(self):
          return len(self._queue)
  
  all_files = []
  for root, _, files in os.walk(root_path):
      base = os.path.join(root_path, root)
      if ".build" in base:
          continue
      for file in files:
          if file.endswith('swift'):
              all_files.append(os.path.join(base, file))
  
  mutations = PriorityQueue()
  
  time_s = 0
  time_ms = 0
  
  while True:
      # Undo the mutations after the specific time has elapsed.
      while mutations.len() > 0 and mutations.peek()[0] < time_ms:
          (mutated_file, mutated_line) = mutations.pop()
          with open(mutated_file, 'r', encoding='utf8', newline='\n') as file:
              lines = file.readlines()
          del lines[mutated_line]
          with open(mutated_file, 'w', encoding='utf8', newline='\n') as file:
              file.writelines(lines)
          all_files.append(mutated_file)
  
      start_time = time.perf_counter()
  
      if len(all_files) == 0:
          end_time = time.perf_counter()
  
          # Compute elapsed time.
          elapsed_time_ms = (end_time - start_time) * 1000
          time_ms += elapsed_time_ms
          continue
  
      # Select a random file to mutate and remove it from the files list.
      random_file_idx = random.randint(0, len(all_files) - 1)
      random_file = all_files[random_file_idx]
      del all_files[random_file_idx]
  
      # Read the file into memory.
      with open(random_file, 'r', encoding='utf8', newline='\n') as file:
          lines = file.readlines()
  
      # Select a random place in the file to add a randomly generated string.
      line_idx = random.randint(0, len(lines) - 1)
      lines.insert(line_idx, generate_random_string(random.randint(1, 120)) + '\n')
  
      # Write the mutated file back out.
      with open(random_file, 'w', encoding='utf8', newline='\n') as file:
          file.writelines(lines)
  
      print(f"Mut: {random_file}")
  
      # Record the mutation in our priority queue.
      mutations.push((random_file, line_idx), time_ms + random.randint(10,100))
  
      end_time = time.perf_counter()
  
      # Compute elapsed time.
      elapsed_time_ms = (end_time - start_time) * 1000
      time_ms += elapsed_time_ms
```
</details>

This script occasionally triggers a language server crash as well, but the automatic restart logic makes it invisible to the user (I've just observed the crash in the logs).

I've been running this script against a specific subdirectory in our project. Reproducing takes anywhere from a few seconds to ~10 minutes (many thousands of edits), and usually takes a few minutes. The script eventually crashes failing to write out the modified file, with the file in question being held open by `sourcekit-lsp.exe`. Interestingly, this only ever triggers on one specific file in this subdirectory (and reproduced on this file dozens of times). This file has a diagnostic error reported in it from sourcekit-lsp, but I tried to reproduce that situation on a similar file and was unable to observe the locking issue.

It seems to trigger only when certain files are open in the editor, but it doesn't have to be the actual file that gets locked. I couldn't find a particular commonality between the files where I observed the issue.

**Comment by ahoppen** [comment]
Just an idea from someone who doesn’t know much about Windows file handling: Would it be possible to open all the files in the project in some mode (I don’t know which one, maybe read or write) that would cause sourcekit-lsp or sourcekitd to fail to open the file in exclusive mode (crash/hang/deadlock/whatever). Then we could attach a debugger and see where sourcekit-lsp/sourcekitd is hanging.

**Comment by z2oh** [comment]
This has continued to be tricky to track down, but I _think_ I have a stack trace:

```
00 000000e7`88eff0c8 00007ffb`1694e2eb     KERNELBASE!CreateFileW
01 000000e7`88eff0d0 00007ffb`427c614f     Foundation!$s10Foundation5NSURLC22_resolveSymlinksInPath17excludeSystemDirs21preserveDirectoryFlagAA3URLVSgSb_SbtFSvSPys6UInt16VGXEfU_+0x5b [C:\a\swift-build\swift-build\SourceCache\swift-corelibs-foundation\Sources\Foundation\NSURL.swift @ 931] 
02 000000e7`88eff140 00007ffb`428a6f46     swiftCore!$sSS16_slowWithCString9encodedAs_xq_m_xSPy8CodeUnitQy_GKXEtKs16_UnicodeEncodingR_r0_lF+0x7ff
03 000000e7`88eff2f0 00007ffb`428e2bf6     swiftCore!$ss21__SharedStringStorageCMa+0x96
04 000000e7`88eff360 00007ffb`427c59d3     swiftCore!$sSS8withUTF8yxxSRys5UInt8VGKXEKlF+0xc6
05 000000e7`88eff3e0 00007ffb`1694daa2     swiftCore!$sSS16_slowWithCString9encodedAs_xq_m_xSPy8CodeUnitQy_GKXEtKs16_UnicodeEncodingR_r0_lF+0x83
06 000000e7`88eff490 00007ffb`169e187a     Foundation!Foundation::_resolveSymlinksInPath+0x152 [C:\a\swift-build\swift-build\SourceCache\swift-corelibs-foundation\Sources\Foundation\NSURL.swift @ 935] 
07 000000e7`88eff560 00007ff7`1a800666     Foundation!$s10Foundation3URLV23resolvingSymlinksInPathACyF+0x5a
08 000000e7`88eff5b0 00007ff7`1a7f63ca     sourcekit_lsp!SKCore::JSONCompilationDatabase::subscript.get+0x76 [C:\a\swift-build\swift-build\SourceCache\sourcekit-lsp\Sources\SKCore\CompilationDatabase.swift @ 182] 
09 000000e7`88eff620 00007ffb`aac967b6     sourcekit_lsp!SKCore::buildSettings+0xda [C:\a\swift-build\swift-build\SourceCache\sourcekit-lsp\Sources\SKCore\CompilationDatabaseBuildSystem.swift @ 106] 
0a (Inline Function) --------`--------     swift_Concurrency!swift::AsyncTask::runInFullyEstablishedContext+0x10 [C:\a\swift-build\swift-build\SourceCache\swift\include\swift\ABI\Task.h @ 363] 
0b 000000e7`88eff6b0 00007ffb`aac96fe2     swift_Concurrency!swift::runJobInEstablishedExecutorContext+0x146 [C:\a\swift-build\swift-build\SourceCache\swift\stdlib\public\Concurrency\Actor.cpp @ 246] 
0c (Inline Function) --------`--------     swift_Concurrency!swift_job_runImpl+0x5d [C:\a\swift-build\swift-build\SourceCache\swift\stdlib\public\Concurrency\Actor.cpp @ 1757] 
0d 000000e7`88eff720 00007ffb`cc81a492     swift_Concurrency!swift_job_run+0x62 [C:\a\swift-build\swift-build\SourceCache\swift\stdlib\public\CompatibilityOverride\CompatibilityOverrideConcurrency.def @ 114] 
0e (Inline Function) --------`--------     dispatch!_dispatch_continuation_invoke_inline+0x7a [C:\a\swift-build\swift-build\SourceCache\swift-corelibs-libdispatch\src\inline_internal.h @ 2455] 
0f (Inline Function) --------`--------     dispatch!_dispatch_continuation_pop_inline+0xd7 [C:\a\swift-build\swift-build\SourceCache\swift-corelibs-libdispatch\src\inline_internal.h @ 2498] 
10 000000e7`88eff790 00007ffb`cc81a324     dispatch!_dispatch_continuation_pop+0xf2 [C:\a\swift-build\swift-build\SourceCache\swift-corelibs-libdispatch\src\queue.c @ 287] 
11 000000e7`88eff7f0 00007ffb`cc823a8b     dispatch!_dispatch_async_redirect_invoke+0x104 [C:\a\swift-build\swift-build\SourceCache\swift-corelibs-libdispatch\src\queue.c @ 801] 
12 (Inline Function) --------`--------     dispatch!_dispatch_continuation_pop_inline+0x36 [C:\a\swift-build\swift-build\SourceCache\swift-corelibs-libdispatch\src\inline_internal.h @ 2496] 
13 (Inline Function) --------`--------     dispatch!_dispatch_root_queue_drain+0x12b [C:\a\swift-build\swift-build\SourceCache\swift-corelibs-libdispatch\src\queue.c @ 6114] 
14 (Inline Function) --------`--------     dispatch!_dispatch_worker_thread+0x1ee [C:\a\swift-build\swift-build\SourceCache\swift-corelibs-libdispatch\src\queue.c @ 6249] 
15 000000e7`88eff870 00007ffb`e90c9363     dispatch!_dispatch_worker_thread_thunk+0x21b [C:\a\swift-build\swift-build\SourceCache\swift-corelibs-libdispatch\src\queue.c @ 6271] 
16 000000e7`88eff930 00007ffb`ea44257d     ucrtbase!thread_start<unsigned int (__cdecl*)(void *),1>+0x93
17 000000e7`88eff960 00007ffb`eb4caa58     KERNEL32!BaseThreadInitThunk+0x1d
18 000000e7`88eff990 00000000`00000000     ntdll!RtlUserThreadStart+0x28
```

We've noticed this issue only triggering on certain files, so this stack trace was obtained by setting a conditional breakpoint on `CreateFileW` when run against a specific path, and then manually observing that the lock remained open after resuming execution (imperfect, but my attempts at verifying the lock state programmatically from within the debugger didn't work).

The code this points to the following code block: https://github.com/apple/swift-corelibs-foundation/blob/77af9c5a984f40e186c0ba127cff88f2a2588c15/Sources/Foundation/NSURL.swift#L921-L947

Which doesn't have any logic bugs that I can see. The file handle is closed in a defer block guarded by handle validity, so I'm not sure what would prevent the actual handle close from happening.

**Comment by tristanlabelle** [comment]
One idea: can you check the return value of that `CreateFileW` (in `rax`) and see if the matching `CloseHandle` gets executed?
