### ISSUE TITLE
multi-module use cases are completely broken: could not open compilation database

### ISSUE THREAD

**Issue by tayloraswift** [apple/sourcekit-lsp#666]
multi-module use cases appear to be completely broken. if i have a module named `A` with example code:

```swift
// A.swift
public
enum A
{
    struct Foo
    {
    }
}
extension A.Foo
{
    func test(x _:Int)
    {
    }
}
```

i get normal highlighting and LSP features, though it emits an error to the console:

```
2022-11-13 18:22:26.497 sourcekit-lsp[393:402dc700] could not open compilation database for /example/Sources/A/A.swift
```

if i go to another module that imports `A`, sourcekit-lsp doesn’t seem to work at all.

```swift
// B.swift
import A

extension A
{
    struct Bar
    {
    }
}
extension A.Bar
{
    func test(x _:Int)
    {
    }
}
```

it also emits a similar error to the console:

```
2022-11-13 18:27:00.923 sourcekit-lsp[393:402dc700] could not open compilation database for /example/Sources/B/B.swift
```

but because it also emits the same error in `A.swift`, i am not sure if the error is related to this issue.

here is a full example project, including a `.devcontainer` directory for reproduction:

[vscode-example.zip](https://github.com/apple/sourcekit-lsp/files/9997962/vscode-example.zip)

the specific toolchain i am using currently is `swift-DEVELOPMENT-SNAPSHOT-2022-11-11-a`, but the problem has been going on for most of november.

**Comment by kelvin13** [comment]
more forum context: https://forums.swift.org/t/vscode-swift-getting-really-flaky-again/61403/2

**Comment by ahoppen** [comment]
rdar://102321349

**Comment by ahoppen** [comment]
When trying to open the project in the devcontainer locally, I’m getting the following error. Do you know what I might be doing wrong here?

```
ERROR: The Compose file is invalid because:
Service swift has neither an image nor a build context specified. At least one must be provided.
```

@adam-fowler Is the devcontainer setup something that the Swift VSCode extension supports (and that is actively being used)? Could it be that the VSCode extension is building the package on the host (with a toolchain from the host) but writing the build products to the containers build directory?

**Comment by adam-fowler** [comment]
@ahoppen Swift extension works fine with devcontainers, well at least up to swift 5.7. The error message implies there is something wrong with the devcontainer setup in the example. Maybe @kelvin13 can help

**Comment by kelvin13** [comment]
i don’t get that error when i open the example project locally, but according to [this SO question](https://stackoverflow.com/questions/52283952/docker-compose-build-image-or-build-context) it could have to do with the service name `swift` (which is a common service name, i imagine) conflicting with a `docker-compose.override.yml` file somewhere on your system.

so maybe try renaming the service name `swift` (in `docker-compose.yml` and `devcontainer.json`) to something more unique?

**Comment by ahoppen** [comment]
AFAICT there’s nothing actionable for sourcekit-lsp here, so I’m closing the issue. Feel free to re-open it if you believe there’s a SourceKit-LSP issue that needs to be fixed.
