### ISSUE TITLE
Update log message to public level

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/sourcekit-lsp#675]
The current log will be `<private>` to end user unless the user is debugging on it.

And it makes the log message of SourceKit a bit of useless.

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/43724855/205721203-596567a3-9814-43aa-9c95-0e03685595fb.png">

> Inspired by digging the original issue https://github.com/apple/swift/issues/62274#issuecomment-1337940045

I think we could improve the logger method to add public modifier
```swift
os_log("%{public}@", log: xx, type: .info, xx) // If we use old API
Logger().info("\(xx, privacy: .public)") // If we can drop macOS 10.15- Support to use new API
```

**Comment by ahoppen** [comment]
rdar://102990224

**Comment by ahoppen** [comment]
I agree that the current situation is not ideal.

But I think the tricky bit is that the log message might contain potentially privacy-sensitive information that we don’t want to log, so marking the entire opaque string is not an option IMO. So each `log` call would need to decide which information it wants to mark as public and private.

**Comment by ahoppen** [comment]
I redesigned the logging infrastructure in https://github.com/apple/sourcekit-lsp/pull/859 and now log calls can specify which parts should be public and which ones should be private. All log calls should now log some public information.

**Comment by Kyle-Ye** [comment]
> I redesigned the logging infrastructure in #859 and now log calls can specify which parts should be public and which ones should be private. All log calls should now log some public information.

I see it was merged into main. Is there a plan to cherry-pick it to release/5.10?

**Comment by ahoppen** [comment]
That refactoring is quite an invasive change to the entire codebase and I don’t plan to cherry-pick it to `release/5.10` which doesn’t contain any of the commits that the PR relies on.
