### ISSUE TITLE
Error on requests that include compiler arg -enable-bare-slash-regex

### ISSUE THREAD

**Issue by charshep** [apple/sourcekit-lsp#687]
I'm seeing an error reported when issuing requests that include the compiler arg -enable-bare-slash-regex.

With log level set to debug I see the following:

error response (Request Failed): error: unknown argument: '-enable-bare-slash-regex'

**Comment by ahoppen** [comment]
rdar://103855479

**Comment by CodaFi** [comment]
@ahoppen Does this have anything to do with the legacy driver being involved in SourceKit requests?

**Comment by ahoppen** [comment]
Which `sourcekit-lsp` version are you seeing this issue with? It’s expected that `-enable-bare-slash-regex` will not work with `sourcekit-lsp` prior to Xcode 14 and since you’re having issues with that `sourcekit-lsp` executable (https://github.com/apple/sourcekit-lsp/issues/688), I’m thinking you might be using `sourcekit-lsp` from Xcode 13.4.1

**Comment by charshep** [comment]
It's definitely the version that ships with XCode 14.1.0. I'm using a test project derived from XCode's "new iOS app" project template that's created and built with XCode 13.4.1 toolchain, and the compile commands in that case don't include `-enable-bare-slash-regex`. Then for 14.1.0 I created a duplicate of the same test project using the same "new iOS app" project template. That's the only version that includes `-enable-bare-slash-regex` in the compile commands.

**Comment by charshep** [comment]
My apologies. It turns out this was indeed a misconfiguration on my part. This issue can be closed.

**Comment by ahoppen** [comment]
OK, out of curiosity: What was the problem? Or was it just something really stupid? Just in case somebody else stumbles across it.

**Comment by charshep** [comment]
Something really stupid. I had an environment variable, `SOURCEKIT_TOOLCHAIN_PATH`, that wasn't getting updated and was pointing to the wrong version of the toolchain path. I missed it because I thought all the relevant variables were defined within emacs itself.
