### ISSUE TITLE
textDocument requests hang

### ISSUE THREAD

**Issue by charshep** [apple/sourcekit-lsp#688]
Since upgrading to XCode 14 all `textDocument` commands hang indefinitely, e.g., `definition`, `references`, `hover`, `documentHighlight`, etc. 

Using `--log-level debug` does not indicate anything additional other than confirming that no response is received until the client cancels the request.

It seems as though `sourcekit-lsp` might have crashed or frozen as I see the following message in my client logs when I restart the server:

> LSP :: Restarting sourcekit-ls:5159
LSP :: sourcekit-ls has exited (killed: 9)
LSP :: Connected to [sourcekit-ls:5514/starting (project root)].
LSP :: sourcekit-ls:5514 initialized successfully in folders: (project root)
**LSP :: Sending to process failed with the following error: Process sourcekit-ls not running**

My environment is XCode 14.1.0 and I'm using the `sourcekit-lsp` binary that's included with it, not a custom build. My lsp client is emacs 28.1 with the lsp-sourcekit package. The previous working version was XCode 13.4.1.

I can provide further details such as the logs when running with `--log-level debug`, my configurations, etc.

For anyone who may have read my earlier report #687, this is happening after removing the `-enable-bare-slash-regex` compiler flag.

**Comment by ahoppen** [comment]
rdar://103858284

**Comment by ahoppen** [comment]
This might be a dump question but could you check whether your editor is misconfigured? The logs you attached mention `sourcekit-ls` instead of `sourcekit-lsp`.

If that’s not the problem, could you try the following to debug the issue?
- In Activity Monitor set View -> Update Frequency -> Very Often (1s), search for `sourcekit-lsp` and open your editor. Check whether `sourcekit-lsp` actually gets launched
- In Console.app in the “Crash Reports” section, look for crash reports of `sourcekit-lsp`
- Try if `sourcekit-lsp` works with a different editor like VSCode
- I don’t know about the `lsp-sourcekit` package for emacs but an LSP log that shows all LSP messages would be super useful to figure out what might be going wrong.

**Comment by charshep** [comment]
Thanks for the feedback and apologies for the "Doesnt werk plz fix" bug report, but I wasn't sure what would be helpful to include.

- Not sure why the "p" is truncated but it's always been like that in emacs
- From the Activity Monitor I've verified that it's running
- From the Console.app I've verified that it's not crashing
- I probably won't have time to run in VSCode soon but I'll try to get to it

Regarding logs, I re-ran with both 13.4.1 and 14.1 with `--log-level debug` for each. I can still include them if you'd like but the only meaningful difference I saw was a number of entries like the following:

`[2023-01-04 18:47:48.936] SourceKitServer: Notification<$/cancelRequest>(`
  `clientID: ObjectIdentifier(0x00006000024d9500),`
  `params: CancelRequestNotification(id: 1671)`
`)`

Seemingly one for each document related action being performed, e.g., `documentHilight`. Does that suggest that there's an issue one level up in the stack? That would be emacs `lsp-mode` in this case.

**Comment by ahoppen** [comment]
Those `--log-level debug` logs would be useful to figure out what’s going wrong.

**Comment by charshep** [comment]
Emacs maintains two log files (buffers actually) for each sourcekit process: `sourcekit-ls::stderr` and `lsp-log: sourcekit-ls:<pid>`. I've attached them here. I generated them from test runs that use a minimal project that replicates the issue. The project being the default iOS app that XCode generates when you select "New Project..." -> "App" and then the only change to that project I made was that I disabled `-enable-bare-slash-regex` in order to avoid #687. I'm using BSP to export my compile commands.

I ran this test twice, once with the project created and built with XCode 13.4.1 in which lsp works. And once with an identical project created and built with XCode 14.1.0, which replicates the issue. The operations that are traced are:

1. Start lsp while the cursor is positioned on a class name such that a `hover` request will be issued
2. With the cursor in the same position, issue a "go to definition" command for the same class such that a `textDocument/definition` request is issued

In the 14.1.0 trace, `$/cancelRequest`s get issued for each `textDocument` request. In the case of the `textDocument/definition` the `cancelRequest` is actually being generated by me. It hangs indefinitely with nothing printed in the log whatsoever until I issue this cancel. For the others, I think a timeout is being generated since those are "automatic" commands that aren't explicitly issued by the user, e.g. `hover`.

Thanks again for your help.


[lsp_13_4_1_log.txt](https://github.com/apple/sourcekit-lsp/files/10356519/lsp_13_4_1_log.txt)
[sourcekit_log_13_4_1.txt](https://github.com/apple/sourcekit-lsp/files/10356522/sourcekit_log_13_4_1.txt)
[lsp_14_1_0_log.txt](https://github.com/apple/sourcekit-lsp/files/10356523/lsp_14_1_0_log.txt)
[sourcekit_log_14_1_0.txt](https://github.com/apple/sourcekit-lsp/files/10356524/sourcekit_log_14_1_0.txt)

**Comment by charshep** [comment]
Sorry, I think I may have ham fisted the debug configuration in my previous run. Here's the full debug output again for both 13.4.1 and 14.1.0. Again, they are runs from two different projects each created from their respective versions of XCode but otherwise the projects are identical. Similarly, the version of sourcekit-lsp that's run with each corresponds to either 13.4.1 or 14.1.0 as well.
[sourcekit_debug_13_4_1.txt](https://github.com/apple/sourcekit-lsp/files/10364558/sourcekit_debug_13_4_1.txt)
[sourcekit_debug_14_1_0.txt](https://github.com/apple/sourcekit-lsp/files/10364611/sourcekit_debug_14_1_0.txt)

**Comment by charshep** [comment]
My apologies. It turns out this was indeed a misconfiguration on my part. This issue can be closed.
