### ISSUE TITLE
sourcekit-lsp does not recognize actor names as types

### ISSUE THREAD

**Issue by tayloraswift** [apple/sourcekit-lsp#694]
sourcekit-lsp is able to provide semantic highlights for `enum`, `struct`, `class`, `protocol`, and `typealias` type identifiers.

however, it is unable to highlight `actor` types as type identifiers. the following table summarizes the observed behavior under `swift-5.8-DEVELOPMENT-SNAPSHOT-2023-01-09-a`

```
$ swift --version
Swift version 5.8-dev (LLVM 08f7fecaf6cedb8, Swift a0b3f802c2ce715)
Target: x86_64-unknown-linux-gnu
```

| type | semantic token |
| ---- | -------------- |
| `enum` | `enum` |
| `struct` | `struct` |
| `class` | `class` |
| `actor` | **`identifier`** * |
| `protocol` | `interface` |
| `typealias` | `typeParameter` |

ideally we should have:

| type | semantic token |
| ---- | -------------- |
| `actor` | **`actor`** |

here is a screenshot:

![image](https://user-images.githubusercontent.com/2556986/214161174-fddaaac0-cab8-4e5b-b12d-d192daa971c4.png)

the following test file may be helpful to investigate the issue:

```swift
enum EnumType
{
    case e
}
actor ActorType
{
    init()
    {
    }
}
final
class ClassType
{
    init()
    {
    }
}
struct StructType
{
    init()
    {
    }
}
protocol ProtocolType
{
}
typealias Typealias = ProtocolType

func test(_:any ProtocolType, _:any Typealias)
{
    let a:ActorType = .init()
    let c:ClassType = .init()
    let s:StructType = .init()
    let e:EnumType = .e
}
```

**Comment by ahoppen** [comment]
rdar://104573568
