### ISSUE TITLE
Server crashing after typing opening brace of enum cases with associated values

### ISSUE THREAD

**Issue by logancollins** [apple/sourcekit-lsp#695]
Hello!

We are encountering an issue with SourceKit-LSP when used with [Nova](https://nova.app). The language server works properly in nearly every situation, but we are tracking a reproducible crash that most often seems to surface when typing the opening bracket of an enum case which has associated values.

Attempts to restart the server will crash in a loop until the document is modified (either by removing the expression or finishing it out, including associated values), seemingly from the contents of the document still containing the empty bracket(s) of the case.

![2023-01-23 14 25 11](https://user-images.githubusercontent.com/714246/214163887-24f75114-e79c-4529-9b5a-a957f3ea2af9.gif)

A bit of background: I'm a developer on the Nova project. We are working to support Swift with a first-party extension from us in tandem with SourceKit-LSP and SwiftPM. So far it's been going very smoothly!

It's possible that this might be some incompatibility between Nova and SourceKit-LSP that I've yet to be able to track down, especially since (presumably) everyone else is using it with other IDEs without seeing a crash like this. However, as far as I can tell, we're fully adherent to LSP spec around document synchronization and such and I cannot for the life of me track down what might be wrong. The way the server crashes makes me feel it's not just a simple LSP incompatibility, though, or at least an issue in SourceKit-LSP's error handling of telling us what we might be doing wrong.

We have not yet tried to build SourceKit-LSP from source alongside the current upstream Swift toolchain. If you feel that there might be changes in the repository that have not yet made it into Xcode, we can attempt to set up that environment. The last time I tried regressing this and building from source, I believe it still reproduced, but that was a few weeks ago at the least (before the recent holiday season).

I'm attaching a sample project and crash report to the end of this issue. If I can provide more information or debugging assistance, please let me know.

Thank you for any help you might be able to provide! 🙏 

### Environment

- macOS 13.1
- SourceKit-LSP provided with Xcode 14.2

### Attachments:

- Crash report (unsymbolicated): 
[sourcekit-lsp-2023-01-23-142015.ips.zip](https://github.com/apple/sourcekit-lsp/files/10484146/sourcekit-lsp-2023-01-23-142015.ips.zip)
- Example project: [Example.zip](https://github.com/apple/sourcekit-lsp/files/10484147/Example.zip)

**Comment by ahoppen** [comment]
rdar://104574396

**Comment by logancollins** [comment]
Oh, and if the team needs to reproduce this _in Nova_, I can provide a pre-release build of the app and extension to do so. 👍

**Comment by adam-fowler** [comment]
I've seen similar bugs with parenthesis in VS Code. See #635.
This fix is in swift 5.7.2 for Linux, but doesn't seem to have made it into the macOS version yet

**Comment by logancollins** [comment]
I believe it's resolved! Thank you / the team for the work in fixing it!
