### ISSUE TITLE
SourceKit-LSP overwriting results of `swift package update`

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#707]
If I run a `swift package update` on a project that has SourceKit-LSP running on it. The results of the update are overwritten by SourceKit-LSP.

If I have a dependency on a package `from: 1.0.0` and I currently have version `1.0.1` but a `1.0.2` has been released when I run `swift package update` I would expect it to update to using version `1.0.2`. It appears when SourceKit-LSP is running the version updates to `1.0.2` and then is reverted back to `1.0.1`.

This is with swift 5.7 and running inside VSCode.

**Comment by ahoppen** [comment]
rdar://105173375
