### ISSUE TITLE
Nothing happen in SublimeText4, Windows10

### ISSUE THREAD

**Issue by daniele-niero** [apple/sourcekit-lsp#714]
Hello,

I'm unable to get sourcekit-lsp to work with SublimeText4 in Windows. 
There are no errors reported, simply nothing happens.

Sublime LSP plugin is installed in Sublime.
Swift is regularly installed in the system, version 5.7
Visual Studio Code (with Swift extension installed) works just fine.

this are my settings, like suggested [here](https://github.com/apple/sourcekit-lsp/blob/main/Editors/README.md):
```json
{
    "log_debug": true,
    "clients": {
      "SourceKit-LSP": {
         "enabled": true,
         "command": [
            "sourcekit-lsp"
         ],
         "selector": "source.swift",
         "languages": [
            {
               "scope": ["source.swift"],
               "languageId": "swift",
               "syntaxes": [
                  "Packages/Decent Swift Syntax/Swift.sublime-syntax",
                ],
            }
         ]
      },
   },
}
```

Any help will be appreciated

**Comment by ahoppen** [comment]
rdar://105448006

**Comment by daniele-niero** [comment]
> rdar://105448006

Sorry, I'm not sure what this is supposed to mean.

**Comment by benlangmuir** [comment]
> Sorry, I'm not sure what this is supposed to mean.

You can ignore the radar link; it's a reference to our internal bug tracking system.

**Comment by daniele-niero** [comment]
> > "scope": ["source.swift"],
>
> This should be "scopes" with an "s".

This didn't make any difference, unfortunately

> > "Packages/Decent Swift Syntax/Swift.sublime-syntax",
>
> Have you installed this package?

Yes of course, it is installed.

There is another thing I actually didn't mentioned initially, and is that I have to add some location to the system PATH, in the LSP's configuration, even if those path **are** in my system path already.
The very strange thing is that I have to add these, to the configuration part of my Sublime Project's file. It doesn't work if I add it to the LSP's configuration file, like the rest of the setup above.

This is my sublime-project file
```json
{
    "folders":
    [
        {
            "path": ".",
        },
    ],
    "settings": {
        "LSP": {
            "SourceKit-LSP": {
                "env": {
                    "PATH": "%PATH%;C:\\Library\\Developer\\Toolchains\\unknown-Asserts-development.xctoolchain\\usr\\lib\\swift\\pm\\ManifestAPI;C:\\Program Files\\swift\\runtime-development\\usr\\bin"
                 },
                "enabled": true
            },
        },
}
```

Without that setting of PATH in the "env" section, I got errors like these:
![image](https://user-images.githubusercontent.com/967740/218972215-af866425-7d67-4f33-b906-233795cbdb2e.png)
![image](https://user-images.githubusercontent.com/967740/218972721-54d71c16-5f81-408e-ab7a-6d9c359ac619.png)

An I've reinstalled Swift a couple times :/

**Comment by benlangmuir** [comment]
> sourcekit-lsp seems to start after all this
> And I can see the process running in the Windows' Task Manager, but nothing happen if I hover over some swift code in the project :/

Okay, if the service is running, do you get any log output? I see you have 'log_debug' enabled, could you also add 
```
  "log_debug": true,
  "log_payloads": true,
  "log_server": true,
  "log_stderr": true,
```

And look for log messages after opening a swift file
* In Sublime's console (ctrl+`)
* In the LSP log window (Command >LSP: Toggle Log Panel)

**Comment by ahoppen** [comment]
I’m closing this issue since it’s been sitting here a while without actionable data for SourceKit-LSP. Feel free to re-open it if you are able to provide more logging data.
