### ISSUE TITLE
Sourcekit-LSP crashes when file doesn't end in a newline

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#718]
Sourcekit-LSP crashes when file doesn't end in a newline. Although this only seems to occur when editing files inside an SwiftPM project.
Steps to reproduce:
1. Open any SwiftPM project in VSCode
2. Open a source file from this project
3. Go to end of file and delete newlines
4. Wait. SourceKit-LSP crashes
5. Add newline back in, and restart the server and everything is ok

Swift version : Swift version 5.8-dev (LLVM 08f7fecaf6cedb8, Swift 7632e9a645bcb05)
Using `swiftlang/swift:nightly-5.8-jammy` docker image tagged `swift-5.8-DEVELOPMENT-SNAPSHOT-2023-01-13-a`

**Comment by ahoppen** [comment]
Hey Adam,

Are you only seeing the crashes on Linux? I just tried reproducing this on macOS and am not seeing any crashes – neither of SourceKit-LSP nor of sourcekitd. I’m using `swift-5.8-DEVELOPMENT-SNAPSHOT-2023-02-23-a` See that attached screen recording for what I did


[Screen Recording](https://user-images.githubusercontent.com/4062178/223594879-e4433c40-9d61-4e3e-a37b-4b1889ae1b1a.mov)

**Comment by adam-fowler** [comment]
I saw this in a swift-5.8-DEVELOPMENT-SNAPSHOT-2023-01-13-a docker image but cannot replicate in
swift-5.8-DEVELOPMENT-SNAPSHOT-2023-02-23-a. I'll close this just now, and re-open if I see it again

**Comment by ahoppen** [comment]
Weird. Anyway, thanks for double-checking.
