### ISSUE TITLE
Does it require that an iphone is connected? 

### ISSUE THREAD

**Issue by hkbluesky** [apple/sourcekit-lsp#727]
Does it require that an iphone is connected? 
It seems this is true in my case. Thanks

![image](https://user-images.githubusercontent.com/47656333/231048234-4d93ab2d-9348-4e68-a799-c6ef980db351.png)

**Comment by ahoppen** [comment]
rdar://107865573

**Comment by ahoppen** [comment]
iPhones are not required for SourceKit-LSP. When does this happen to you? If you open the file or when you hit build? Also, could you share 
- Your `launch.json`
- Any settings in your VSCode Swift extension that differ from the defaults.

**Comment by hkbluesky** [comment]
Hi, do you have a default launch.json that I can use to test it? My launch.json may have some problems.

**Comment by ahoppen** [comment]
I do not. `launch.json` also isn’t something that’s part of SourceKit-LSP (which is just the LSP server that provides the semantic functionality) but by VSCode or the Swift VSCode Extension (https://github.com/swift-server/vscode-swift). If you are seeing this issue while building, can you close this issue and re-open one in that repository?

**Comment by ahoppen** [comment]
@hkbluesky Are you seeing the error while building or while editing? If you are seeing this issue while building, can you close this issue and re-open one in that repository?

**Comment by hkbluesky** [comment]
I am seeing this issue while building. But I feel it is too difficult to use this SourceKit-LSP. So, I give up.
