### ISSUE TITLE
Sourcekit-LSP features are not available when editing a macro

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#754]
Sourcekit-LSP returns no result for all requests when editing a macro's source code.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://110516429

**Comment by adam-fowler** [comment]
Could be related to #664

**Comment by ahoppen** [comment]
I wasn’t able to reproduce this with the following steps:

1. Create a new macro from the SwiftPM template
2. Build the package
3. Perform code completion for `print` in MyMacro/MyMacro.swift, MyMacroClient/main.swift and MyMacroMacros/MyMacroMacros.swift. In all of those files, I received code completion results.

**Comment by adam-fowler** [comment]
Try getting code completion for a symbol in swift-syntax, for instance `ExpressionMacro`

**Comment by ahoppen** [comment]
It’s working for me…

<img width="1392" alt="Screenshot 2023-07-06 at 14 29 09" src="https://github.com/apple/sourcekit-lsp/assets/4062178/fa8ea613-f320-4685-a37c-2695f3947389">

**Comment by adam-fowler** [comment]
Ok this looks like this is related to the bad version of sourcekit-lsp that was released with the Xcode beta, latest 5.9 is working fine
