### ISSUE TITLE
InlayHint textEdits are not always correct

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#759]
The text edits supplied with InlayHints don't always provide code that will compile eg adding the inlay hint to a closure argument would generate invalid code
```swift
func test(_ process: (String) -> ()) {
    process("hello")
}
test { string in 
    print(string)
}
```
The inlay hint for string is `: String`. The text edit that goes along with it is the same and inserting it would generate the following code

```swift
test { string: String in
    print(string)
}
```
which does not compile.

Another example is enums with associated values
```swift
case .test(let value):
```
becomes
```swift
case .test(let value: (String)):
```

Maybe we should disable the text edit option until we can be sure it returns valid code.

See https://github.com/swift-server/vscode-swift/issues/554 where this was originally reported

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://111559715
