### ISSUE TITLE
Does SourceKit-LSP support the -sdk parameter

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#760]
The VS Code extension has an option to compile using different Xcode tool sets. It uses the `--sdk` parameter when running swift. This is automatically passed to sourcekit-lsp as well as `-sdk`. Is this fully supported though?

I find when running with `-sdk` I get symbol completion for symbols from the local module but cannot get symbol completion for any symbols from other modules

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://111566900

**Comment by ahoppen** [comment]
Are you pointing `--sdk` to an SDK from a  different Xcode installation or e.g. to an iOS SDK of the same Xcode that your toolchain is from?

**Comment by adam-fowler** [comment]
iOS of the same Xcode

**Comment by ahoppen** [comment]
Are you able to reproduce the issue? I just set my SDK to and did get global completions for other modules while completing in the attached project.

<img width="1348" alt="Screenshot 2023-07-07 at 20 00 56" src="https://github.com/apple/sourcekit-lsp/assets/4062178/69a408af-d876-4b17-b9a1-f7fd75d094ee">

[pck2.zip](https://github.com/apple/sourcekit-lsp/files/11984673/pck2.zip)

**Comment by adam-fowler** [comment]
Yes it is working in the end. It isn't listed in the `--help` output though

**Comment by ahoppen** [comment]
Where isn’t `--help` documented? You pass it to `sourcekit-lsp` as `-Xswitc -sdk -Xswiftc <sdk path>`

**Comment by adam-fowler** [comment]
Ok maybe that's why.
