### ISSUE TITLE
Improve handling of unmet protocol conformance

### ISSUE THREAD

**Issue by compnerd** [apple/sourcekit-lsp#776]
It is unclear if this is a LSP issue or a VSCode issue, but the protocol conformance requirements are not listed in the diagnostic emitted.  The hover card in VSCode is unable to emit/display the missing requirements.  The VScode light bulb does however seem to be able to synthesize the missing protocol requirements.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://112539108

**Comment by benlangmuir** [comment]
> light bulb actions (whatever they're called in LSP parlance)

["Code Action"](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction) where "QuickFix" is a specific kind.

> Shouldn't there be a way to reference light bulb actions (whatever they're called in LSP parlance) from diagnostics so that instead of "No quick fixes available" in the hover it was able to pick those up?

We should already be [finding quick fixes from the most recent diagnostics when looking up code actions](https://github.com/apple/sourcekit-lsp/blob/2a3b8340491ff50197744267b2f38f905067dd48/Sources/SourceKitLSP/Swift/SwiftLanguageServer.swift#L1282); one issue is that diagnostic locations may not overlap where the cursor is, particularly if the diagnostic only has a single source location and not a range. Maybe we could teach that code to extend locations out to their token boundaries? Just a guess.

**Comment by ahoppen** [comment]
I’ve got a fix up: https://github.com/apple/sourcekit-lsp/pull/777. We weren’t storing the diagnostics retrieved using the pull-model diagnostics.

**Comment by tristanlabelle** [comment]
Testing with latest:

![image](https://github.com/apple/sourcekit-lsp/assets/2314287/bac0572b-8eef-4e5d-8deb-eb2f7a5da839)

Clicking on `Quick Fix...`:
<img width="388" alt="image" src="https://github.com/apple/sourcekit-lsp/assets/2314287/44c85b48-e5c6-45ce-8c75-8f7b64a7a84b">

Clicking on `do you want to add protocol stubs?`:
<img width="154" alt="image" src="https://github.com/apple/sourcekit-lsp/assets/2314287/d7fe0140-3cd5-4eaa-95c5-aadeccc6c5d3">

Note: the quick fix text is inconsistent with the code action:
<img width="284" alt="image" src="https://github.com/apple/sourcekit-lsp/assets/2314287/7ff865d5-2203-4bd7-9254-c038a5102c6e">

I wonder also if @compnerd had in mind to be able to see the list of missing members in the hover popup in addition to having the fixit available?

**Comment by compnerd** [comment]
Yes, when building on the command line, I can quickly see the missing requirements which means that VSCode/LSP is still a regression.

**Comment by ahoppen** [comment]
> Note: the quick fix text is inconsistent with the code action:

This is actually correct. “do you want to add protocol stubs” is a Fix-It while “Add Missing Protocol Requirements” is a refactoring, so they are coming from two different sources. It’s a little unfortunate that they show up right underneath each other in VS Code but this is the intended behavior.

**Comment by tristanlabelle** [comment]
@ahoppen I filed #781 for this discussion.
