### ISSUE TITLE
Function completion should only insert parameter labels

### ISSUE THREAD

**Issue by tristanlabelle** [apple/sourcekit-lsp#780]
Given `func foo(_ x: Int, y: Int) {}`, if I type `foo(`...

# Actual behavior
I am offered `foo(x: Int, y: Int)` in the completion box, and accepting it completes to `foo(x: Int, y: Int)`.

![function-completion](https://github.com/apple/sourcekit-lsp/assets/2314287/c4ae29b8-9df0-4e03-9bbc-c987e8c5721e)

There are a few problems with this:
- The signature shown seems incorrect because the first parameter has no label. It should be `foo(Int, y: Int)`
- Completion includes the first parameter label, which is incorrect because the function cannot be called that way.
- Completion include type names, which is not useful and need to be manually deleted.

# Expected behavior
I am offered `foo(Int, y: Int)` and accepting it completes to `foo(|, y: )`, where `|` represents the cursor position. Note that there is no `x:` label and no types have been inserted so I can immediately fill in with the values I need instead of needing to first erase the types.

Stretch feature: complete last parameters of closure types as trailing blocks.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://112732434

**Comment by ahoppen** [comment]
Actually, this behaves as it is intended: The completion that is offered actually contains two snippets (in Xcode terminology placeholders) and the completion that is offered is the following (I’m using `<>` to indicate the snippets). 

```swift
foo(<x: Int>, y: <Int>)
```

You can then use tab to jump from one snippet to the next. 

https://github.com/apple/sourcekit-lsp/assets/4062178/781a2720-7a51-4781-854c-591676498830

Also, we provide the second parameter name (`x`) to indicate what the parameter without an external argument label is.

If you used an editor that doesn’t support LSP snippets (not sure if you could also turn it off in VS Code), the completion that you will get offered is what you suggested:

```swift
foo(, y: )
```

With that in mind, do you still think that this is a bug or would you say it behaves correctly?

**Comment by tristanlabelle** [comment]
Thanks for clarifying! I agree this is the intended behavior. I thought there were no snippets because they were highlighted so dimly that I didn't notice them.

**Comment by tristanlabelle** [comment]
While I'm here, does XCode use `sourcekit-lsp`, or `sourcekitd` directly?

**Comment by ahoppen** [comment]
Xcode uses sourcekitd directly.
