### ISSUE TITLE
(5.9) attributes incorrectly highlighted as identifiers

### ISSUE THREAD

**Issue by tayloraswift** [apple/sourcekit-lsp#785]
in the current 5.9 nightlies, attributes such as `@frozen`, `@inlinable`, etc. are incorrectly highlighted as identifiers rather than keywords/attributes. this is a regression from 5.8.

VSCode screenshot:

![image](https://github.com/apple/sourcekit-lsp/assets/2556986/7b0271b8-532b-4473-9ce0-0ca803d423f8)

the identifier coloring is visually jarring and cannot be overridden by changing syntax theme definitions, as they are semantically labeled as identifiers.

please note that the *textmate scope* classification, while correct, is irrelevant here, as syntax highlight colors are determined entirely from semantic token type.

```
$ swift --version
Swift version 5.9-dev (LLVM ea47328e7cf304e, Swift 9c3928cc0c738b5)
Target: x86_64-unknown-linux-gnu
```

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://113086754

**Comment by ahoppen** [comment]
For context: we’re discussing fixing this in https://github.com/apple/swift-syntax/pull/1953#discussion_r1278348041.

**Comment by ahoppen** [comment]
This should be fixed on `main` by https://github.com/apple/swift-syntax/pull/1953.
