### ISSUE TITLE
Provide method to search all symbols

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#802]
I don't know if this is possible now, or if it even exists in the LSP spec. In Xcode when I press Shift+Cmd+O I get a symbol search window. Which updates as I type in it. I would like to provide something similar in VS Code. Do you know if something like this exists in LSP?

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://114083978

**Comment by adam-fowler** [comment]
That might do it, I'll check it out

**Comment by adam-fowler** [comment]
Worked out how to get it Cmd+T in VSCode
