### ISSUE TITLE
issue from vscode-swift#587

### ISSUE THREAD

**Issue by MartinLau7** [apple/sourcekit-lsp#803]
issue from [vscode-swift#587](https://github.com/swift-server/vscode-swift/issues/587)

It seems that source-kit has provided some error values
![](https://user-images.githubusercontent.com/5416852/262270874-b6493abf-da79-40dd-ba18-0386c343618a.gif)

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://114428202

**Comment by ahoppen** [comment]
Thanks for the bug report. Just posted a PR to fix this: https://github.com/apple/sourcekit-lsp/pull/804

**Comment by MartinLau7** [comment]
Will this change be included in version 5.8 or the upcoming 5.9?

**Comment by ahoppen** [comment]
The fix is too late to make it into 5.9 and will be included in Swift 5.10.
