### ISSUE TITLE
This approach works for Neovim

### ISSUE THREAD

**Issue by TyrfingMjolnir** [apple/sourcekit-lsp#805]
https://gist.github.com/TyrfingMjolnir/b4b750d0f944e855a683024e646a6487

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://114555652

**Comment by ahoppen** [comment]
@TyrfingMjolnir What are you trying to say with this issue? We already have documentation of how to set up sourcekit-lsp with neovim https://github.com/apple/sourcekit-lsp/blob/main/Editors/README.md#vim-8-or-neovim. If you have suggestions of how to improve it, pull requests are always welcome.e

**Comment by ahoppen** [comment]
I’m closing this issue. As I commented in https://github.com/apple/sourcekit-lsp/pull/810#issuecomment-1788108784, if the existing documentation for `neovim` doesn’t work for you, a PR that adjust the existing example would be appreciated.

**Comment by TyrfingMjolnir** [comment]
Where did you move this page? https://github.com/apple/sourcekit-lsp/blob/main/Editors/README.md#vim-8-or-neovim

**Comment by ahoppen** [comment]
https://github.com/swiftlang/sourcekit-lsp/blob/main/Documentation/Editor%20Integration.md is the new URL.
