### ISSUE TITLE
Regex literals appear to be unsupported currently

### ISSUE THREAD

**Issue by tinder-tannerbennett** [apple/sourcekit-lsp#806]
This is via the [swift-server/vscode-swift](https://github.com/swift-server/vscode-swift) extension for VS Code 

<img width="503" alt="Screenshot 2023-08-28 at 9 52 00 PM" src="https://github.com/apple/sourcekit-lsp/assets/89099176/ec0afede-b835-489e-ba21-cf49731ffeb9">

Note that this is not a project with a Package.swift file. I assume this error is not encountered in scenarios where the language server has broader knowledge about the project. But I think it should be supported just as well as String literals are, all the same

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://114608203

**Comment by ahoppen** [comment]
This behaves as expected. If you are compiling the source file using `swiftc /path/to/your/file.swift`. To enable the bare slash regex literal, you need to pass `-enable-bare-slash-regex` to `swiftc`. If you want to do the equivalent for standalone Swift files opened in VS Code, you can do so by adding `-Xswiftc` and `-enable-bare-slash-regex` to the  `swift.sourcekit-lsp.serverArguments` setting.
