### ISSUE TITLE
Better jump to definition for implementations of a protocol

### ISSUE THREAD

**Issue by MahdiBM** [apple/sourcekit-lsp#809]
Consider this code:
```swift
protocol TestProtocol {
    func doThing()
}

struct TestImpl: TestProtocol { 
    func doThing() { }
}

func anyTestProtocol(value: any TestProtocol) {
    value.doThing()
}
```

Using VSCode with SSWG Swift extension, in `value.doThing()`, when you right click on `doThing()` to jump to definition, it'll just automatically jump to the protocol. This seems to be a SourceKit-LSP limitation.

Xcode/sourcekitd though is more smart about it and lets you choose between the protocol or one of the implementations:   

<kbd> <img width="741" alt="Screenshot 2023-09-01 at 6 04 36 PM" src="https://github.com/swift-server/vscode-swift/assets/54685446/3a7905fb-96ba-4c85-a3fd-a420f87cfdef"> </kbd>

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://114864256

**Comment by ahoppen** [comment]
sourcekit-lsp should report the secondary symbols returned by the sourcekitd cursor info response.

**Comment by MahdiBM** [comment]
@ahoppen I assume that's just a note tracking the progress of the issue? Or do I need to do something? 🙂

**Comment by ahoppen** [comment]
Oh, no, that’s just a note to myself what we should do to fix this.
