### ISSUE TITLE
Cursor position at end of symbol, doesn't capture symbol

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#820]
Not sure if this is a VSCode issue or one SourceKit-LSP needs to solve. If you double click on a symbol and then use the context menu to look up references it will fail to find any references. This appears to be because the cursor position sent to Sourcekit-LSP is the end of the symbol and not the beginning.

See https://github.com/swift-server/vscode-swift/issues/602#issuecomment-1721197331 for more details.

**Comment by adam-fowler** [comment]
Had a closer look at this and it appears that VSCode considers the character directly after a symbol as part of the symbol. I guess the test for whether we are in a symbol should be inclusive, `start...end` instead of `start..<end`

**Comment by bnbarham** [comment]
Another case here would be if some whitespace is selected at the end as well. Seems reasonable for us to just look back to find the start of a token prior to any whitespace.

**Comment by adam-fowler** [comment]
> Another case here would be if some whitespace is selected at the end as well. Seems reasonable for us to just look back to find the start of a token prior to any whitespace.

VSCode only seems to care about the first character after the symbol, which isn't necessarily whitespace either it could be some form of grammar eg comma or bracket.

**Comment by bnbarham** [comment]
> VSCode only seems to care about the first character after the symbol

I'm more thinking of eg.
```
_ = someVar + someOther
   ^-------^
```

So the user has specifically included whitespace (rather than double clicking on the identifier).

> which isn't necessarily whitespace either it could be some form of grammar eg comma or bracket.

That's a good point, but then makes me wonder if we should handle this by having VSCode send the start of the range rather than the end. If there was a custom postfix operator for `++`, then we wouldn't be able to differentiate:
```
someVar++
^-----^
vs
someVar++
       ^
```

**Comment by adam-fowler** [comment]
> That's a good point, but then makes me wonder if we should handle this by having VSCode send the start of the range rather than the end

I don't have control over that. I couldn't even edit it via a middleware as I won't have enough information at that point. Also I've always thought of VSCode as the default implementation of an LSP client, given LSP was pretty much written for it.

**Comment by bnbarham** [comment]
When not selecting any range, what position is sent? Is it the `r` or `+` in the following (where | is the cursor location)?
```
someVar|++
```

And just to be clear, it's the position of `+` for:
```
someVar++
^-----^
```
?

**Comment by adam-fowler** [comment]
@bnbarham 
If I place the cursor between the `r` and the `+` as In the first case it will send the position of the `+`
In the second case it will return the position of the `+`
