### ISSUE TITLE
_SourceKitLSP - invalid character in Bundle Identifier

### ISSUE THREAD

**Issue by krzyzanowskim** [apple/sourcekit-lsp#822]
When use with SPM as a dependency, Swift 5.9 (Xcode 15 RC) is not happy about _SourceKitLSP target name:

```
warning: invalid character in Bundle Identifier. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters. (in target '_SourceKitLSP' from project 'SourceKitLSP')
```

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://115633096

**Comment by ahoppen** [comment]
This doesn’t appear to be an Xcode regression. Xcode 14.3 emits the same warning. The fix should be to declare the product as automatic instead of it being declared as `dynamic`. That way Xcode won’t build a framework and thus no Info.plist will get created, which causes the issue.
