### ISSUE TITLE
`closeHandler` callback can be `nil` in an initializer

### ISSUE THREAD

**Issue by AndreyKlebanov** [apple/sourcekit-lsp#852]
https://github.com/apple/sourcekit-lsp/blob/05b3abd4ed8cbea7fa6539ad9deaf8abe8abafcd/Sources/LanguageServerProtocolJSONRPC/JSONRPCConnection.swift#L108

self.closeHanlder callback can be nil in constructor when DispatchIO() fails with _"IO error \(error)"_.

One way to approach this - check if closeHandler as assigned before calling it:
`if (self.closeHandler != nil) { self.closeHandler() }`

Alternatively we could make .init() throwable and throw when IO error happens.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://116460760

**Comment by ahoppen** [comment]
Oh, good catch @AndreyKlebanov. Would you like to open a PR to fix this? I think changing `closeHandler` from an implicitly unwrapped optional to an optional would be a good thing to do in general.

**Comment by ahoppen** [comment]
Fixed by https://github.com/apple/sourcekit-lsp/pull/855
