### ISSUE TITLE
Function completion should leverage trailing closure syntax

### ISSUE THREAD

**Issue by tristanlabelle** [apple/sourcekit-lsp#854]
Given `func foo(a: Int, b: () -> ()) {}`, the completion for `foo` is `foo(a: Int, b: () -> ())` with snippets on the types. It's more swifty to use the trailing closure syntax, so it would be nice for this to be `foo(a: Int) {}`, or some variant inside the closure.

Bonus points if the trailing closure syntax is avoided if the expression is inside of an if / while statement since that generates a warning that the curly braces are confusing.

![completion without trailing closure](https://github.com/apple/sourcekit-lsp/assets/2314287/382a155a-2bb5-4b02-b9d4-bc6299bda092)

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://116470157

**Comment by ahoppen** [comment]
Implemented in https://github.com/apple/sourcekit-lsp/pull/1072.
