### ISSUE TITLE
Include `isFallback` in `FileBuildSettings` instead of returning a tuple

### ISSUE THREAD

**Issue by ahoppen** [apple/sourcekit-lsp#861]
Instead of having `BuildSystemManager.buildSettings` return a tuple of `FileBuildSettings` and `isFallback: Bool`, we should make `isFallback` part of `FileBuildSettings`.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://116703679

**Comment by joehsieh** [comment]
Hello, I'd like to take this issue to onboard myself to this project.

**Comment by ahoppen** [comment]
Thank you. I’m looking forward to a PR 👍🏽

**Comment by joehsieh** [comment]
here is the PR for the refactoring.
https://github.com/apple/sourcekit-lsp/pull/908

**Comment by ahoppen** [comment]
Fixed by https://github.com/apple/sourcekit-lsp/pull/908
