### ISSUE TITLE
Code folding improvements + bugs

### ISSUE THREAD

**Issue by NSExceptional** [apple/sourcekit-lsp#898]
- Multi-line collections cannot be folded at all
- Individual cases in a `switch` cannot be folded at all
- This range folds entirely into a single line when only the comment should be folded; instead, the first line of the decl right below it is also collapsed. 
   <img width="556" alt="Screenshot 2023-10-12 at 11 41 17 AM" src="https://github.com/apple/sourcekit-lsp/assets/89099176/eedc9078-ca69-4fb0-9113-1612ac006707">
- Here, the folding marker is incorrectly on the line above the `return` statement. It is in the correct spot if the comment is removed. It behaves just like the above, where the following line is consumed by folding the comment. I'm guessing this implies all comments should be foldable, but that if a foldable statement exists below a comment, it mistakenly interferes with the ability to fold that statement.
   <img width="630" alt="Screenshot 2023-10-12 at 11 43 03 AM" src="https://github.com/apple/sourcekit-lsp/assets/89099176/a6867f0a-3b00-4560-96d5-9dc6ac711e2a">
   <img width="630" alt="Screenshot 2023-10-12 at 11 45 29 AM" src="https://github.com/apple/sourcekit-lsp/assets/89099176/a64b3b3c-1b18-4156-960f-c317e7007e51">
- Trailing `)`'s are not folded up the way trailing `}`'s are
   <img width="347" alt="Screenshot 2023-10-12 at 11 49 24 AM" src="https://github.com/apple/sourcekit-lsp/assets/89099176/20b5f963-107d-4d08-a5be-a5215d48f3d3">
   Unless they're preceded by a `}`:
   <img width="481" alt="Screenshot 2023-10-12 at 11 52 05 AM" src="https://github.com/apple/sourcekit-lsp/assets/89099176/1aea59a0-ca4d-461c-b1df-e133aaea915e">
   <img width="481" alt="Screenshot 2023-10-12 at 11 53 12 AM" src="https://github.com/apple/sourcekit-lsp/assets/89099176/06b25247-e932-48bc-b24f-2300fd081825">

Edit: Adding more below as I come across them

- Multiline function/init declarations, such as
   ```swift
    func someMethodWithLotsOfArgs( <--- this part
        arg1: T,
        arg2: U,
        arg3: V,
        arg4: W,
        ...
    ) {                            <--- down to here
        ...
    }
   ```

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://116877123

**Comment by ahoppen** [comment]
I think the folding issues with comment should be fixed by https://github.com/apple/sourcekit-lsp/pull/804 but the other issues are definitely also ones we should fix.

**Comment by ahoppen** [comment]
If anyone is interesting in fixing these: The folding ranges are computed in https://github.com/apple/sourcekit-lsp/blob/d043dc068d6955a30f063e4f5550e63516a24d96/Sources/SourceKitLSP/Swift/SwiftLanguageServer.swift#L659, which is a fairly isolated `SwiftSyntax` visitor that doesn’t require too much outside knowledge apart from swift-syntax trees.

Tests live in https://github.com/apple/sourcekit-lsp/blob/main/Tests/SourceKitLSPTests/FoldingRangeTests.swift
