### ISSUE TITLE
Dependencies could not be resolved because root depends on 'swift-crypto' 2.5.0..<3.0.0 and 'swift-package-manager' depends on 'swift-crypto' 3.0.0..<3.1.0.

### ISSUE THREAD

**Issue by joehsieh** [apple/sourcekit-lsp#903]
i was following the [guideline](https://github.com/apple/sourcekit-lsp/blob/main/Documentation/Development.md#building-sourcekit-lsp) to build the project sourcekit-lsp, but the error `error: Dependencies could not be resolved because root depends on 'swift-crypto' 2.5.0..<3.0.0 and 'swift-package-manager' depends on 'swift-crypto' 3.0.0..<3.1.0.` came up to me.

After checking the Package.swift in both repo swift-package-manager and sourcekit-lsp, i think there is a conflict.
Perhaps, the same [revert](https://github.com/apple/swift-package-manager/pull/6988) should be applied on the main branch of swift-package-manager as well. 

swift-package-manager
[.package(url: "https://github.com/apple/swift-crypto.git", .upToNextMinor(from: "3.0.0")),](https://github.com/apple/swift-package-manager/blob/main/Package.swift#L739)

sourcekit-lsp
[ .package(url: "https://github.com/apple/swift-crypto.git", from: "2.5.0"),](https://github.com/apple/sourcekit-lsp/blob/main/Package.swift#L273)

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://116982771

**Comment by MaxDesiatov** [comment]
This revert is unlikely to be applied to the `main` branch of SwiftPM. SourceKit-LSP should update to swift-crypto 3.0 instead.

**Comment by joehsieh** [comment]
ah, okie. if so, let me create a PR to bump the version of swift-crypto to 3.0.0
