### ISSUE TITLE
Remove dependency of `LanguageServerProtocol` on `TSC`

### ISSUE THREAD

**Issue by bnbarham** [apple/sourcekit-lsp#938]
As in https://github.com/apple/sourcekit-lsp/issues/936, `LanguageServerProtocol` should be usable in any context without any dependencies - it's a generally useful module for eg. any LSP client written in Swift to use. Remove the dependency on swift-tools-support-core.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://117565087
