### ISSUE TITLE
Instead of having a `willEditDocument` closure in `DocumentManager.edit` return an array of edits

### ISSUE THREAD

**Issue by ahoppen** [apple/sourcekit-lsp#939]
See https://github.com/apple/sourcekit-lsp/pull/934/files#r1373963800

Instead of calling a `willEditDocument` callback from `DocumentManager.edit`, return an array of edits. `SwiftRefactor.SourceEdit` seems like it could be a good candidate to use for the edit struct.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://117567686

**Comment by mustiikhalil** [comment]
Would love to help with this if its still open

**Comment by ahoppen** [comment]
Yes, please, the issue is still open.

**Comment by mustiikhalil** [comment]
Perfect! I'll start looking at it soon, might need some guidence down the road but that's something for later I guess after ive looked at the code and analyzed it.

**Comment by ahoppen** [comment]
If you have any questions, it’s usually easiest to open a PR with what you’ve got so far and then we can discuss it.
