### ISSUE TITLE
LSP support for Swift shell scripts

### ISSUE THREAD

**Issue by GeorgeLyon** [apple/sourcekit-lsp#964]
I've got a few scripts which are just executable text files with a shebang line (`#!/usr/bin/env swift`) and Swift code and it would be really great if sourcekit-lsp provided LSP support for those. I'm pretty sure just using the shebang command as a compile command would work, but I'm not sure how this would interact with "workspaces". We could have a single shell script "workspace" which has all of the shell scripts, or we can have an individual "workspace" for each shell script. Alternatively, we could just have a fallback when no compile command is found that checks whether the file is executable, reads the first line and if it can parse it into a Swift command, provides LSP support for it. I'm not familiar enough with sourcekit-lsp architecture to determine which of these approaches is most desirable, but if someone else can weigh (@ahoppen?) in I'm happy to try and put together a PR.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://117872298

**Comment by GeorgeLyon** [comment]
Not exactly sure what is going on, but this now works for me out-of-the-box in VSCode. Will re-open if I can break it again.
