### ISSUE TITLE
Issues on Windows Swift 5.9

### ISSUE THREAD

**Issue by adam-fowler** [apple/sourcekit-lsp#982]
The vscode-swift repo has received a number of issues related to sourcekit-lsp crashing on Windows with swift 5.9. These include 

https://github.com/swift-server/vscode-swift/issues/612 high CPU usage at start up and then auto-complete not working
https://github.com/swift-server/vscode-swift/issues/646 SourceKit-LSP stops responding after a few seconds
https://github.com/swift-server/vscode-swift/issues/561 SourceKit Language Server emits errors, autocomplete doesn't work

**Comment by ahoppen** [comment]
According to @compnerd this should be fixed by the following 2 PRs
- https://github.com/apple/swift-corelibs-libdispatch/pull/781
- https://github.com/apple/swift-corelibs-libdispatch/pull/796

**Comment by adam-fowler** [comment]
@compnerd is there a release with these changes?

**Comment by ahoppen** [comment]
The `main` development snapshot should contain the fixes. I also built a 5.9 toolchain with the [libdisaptch cherry-pick](https://github.com/apple/swift-corelibs-libdispatch/pull/802) here and I was able to confirm that it doesn’t have the hang issue anymore: https://ci-external.swift.org/job/swift-PR-build-toolchain-windows/1045/

**Comment by ahoppen** [comment]
This should be fixed by https://github.com/apple/swift-corelibs-libdispatch/pull/802. Let’s close this issue.

**Comment by JoaoVictorVP** [comment]
Is this really fixed tho?
![Image](https://github.com/user-attachments/assets/bb7a62cf-1f98-4214-8fb0-9dc3b1c1e2bc)
I'm having this constant consumpiton in CPU in a completely new project using Swift 6.xxx, this with the latest extension version and all.
